<?php

use Illuminate\Database\Seeder;

class PtsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pts')->delete();
        
        \DB::table('pts')->insert(array (
            0 => 
            array (
                'id' => '1',
                'city_id' => NULL,
                'code' => 'D01',
                'name' => 'PT. CIPUTRA INDAH',
                'address' => 'Jonggol',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '38',
            ),
            1 => 
            array (
                'id' => '2',
                'city_id' => NULL,
                'code' => 'D02',
                'name' => 'PT. MITRAKUSUMA ERASEMESTA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '39',
            ),
            2 => 
            array (
                'id' => '3',
                'city_id' => NULL,
                'code' => 'G01',
                'name' => 'PT. CIPUTRA SURYA - KP',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '46',
            ),
            3 => 
            array (
                'id' => '4',
                'city_id' => NULL,
                'code' => 'G02',
                'name' => 'PT. APTACITRA SURYA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '47',
            ),
            4 => 
            array (
                'id' => '5',
                'city_id' => NULL,
                'code' => 'G03',
                'name' => 'PT. BUMIINDAH PERMAITERANG',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '48',
            ),
            5 => 
            array (
                'id' => '6',
                'city_id' => NULL,
                'code' => 'G04',
                'name' => 'PT. TAMANCITRA SURYAHIJAU',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '49',
            ),
            6 => 
            array (
                'id' => '7',
                'city_id' => NULL,
                'code' => 'G05',
                'name' => 'PT. SUBURHIJAU JAYAMAKMUR',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '50',
            ),
            7 => 
            array (
                'id' => '8',
                'city_id' => NULL,
                'code' => 'G06',
                'name' => 'PT. CAHAYAHIJAU TAMANINDAH',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '51',
            ),
            8 => 
            array (
                'id' => '9',
                'city_id' => NULL,
                'code' => 'G07',
                'name' => 'PT. GALAXY ALAMSEMESTA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '52',
            ),
            9 => 
            array (
                'id' => '10',
                'city_id' => NULL,
                'code' => 'G08',
                'name' => 'PT. GALAXY CITRAPERDANA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '53',
            ),
            10 => 
            array (
                'id' => '11',
                'city_id' => NULL,
                'code' => 'G09',
                'name' => 'PT. CITRA BAHAGIA ELOK',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '54',
            ),
            11 => 
            array (
                'id' => '12',
                'city_id' => NULL,
                'code' => 'G12',
                'name' => 'PT. CIPUTRA ELOK MITRA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '57',
            ),
            12 => 
            array (
                'id' => '13',
                'city_id' => NULL,
                'code' => 'H01',
                'name' => 'PT. CIPUTRA SPIRIT',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:48.000',
                'updated_at' => '2018-10-18 21:45:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '58',
            ),
            13 => 
            array (
                'id' => '14',
                'city_id' => NULL,
                'code' => 'H02',
                'name' => 'PT. SAPTAMULIA HIJAUBANGUN',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '59',
            ),
            14 => 
            array (
                'id' => '15',
                'city_id' => NULL,
                'code' => 'H03',
                'name' => 'PT. INTILOKAHITA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '60',
            ),
            15 => 
            array (
                'id' => '16',
                'city_id' => NULL,
                'code' => 'H04',
                'name' => 'PT. KARYAPRIMA HIJAUSELARAS',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '61',
            ),
            16 => 
            array (
                'id' => '17',
                'city_id' => NULL,
                'code' => 'I01',
                'name' => 'PT. SINAR BAHANA MULYA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '62',
            ),
            17 => 
            array (
                'id' => '18',
                'city_id' => NULL,
                'code' => 'I02',
                'name' => 'PT. CIPTAULUNG ARTAJAYA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '63',
            ),
            18 => 
            array (
                'id' => '19',
                'city_id' => NULL,
                'code' => 'S01',
                'name' => 'PT. WIN WIN REALTY',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '80',
            ),
            19 => 
            array (
                'id' => '20',
                'city_id' => NULL,
                'code' => 'L01',
                'name' => 'PT. UAT Company',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '1091',
            ),
            20 => 
            array (
                'id' => '21',
                'city_id' => NULL,
                'code' => 'ABP',
                'name' => 'PT. Asendabangun Persada',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2088',
            ),
            21 => 
            array (
                'id' => '22',
                'city_id' => NULL,
                'code' => 'CBC',
                'name' => 'JO CIPUTRA KARYA PANCASAKTI NUGRAHA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2092',
            ),
            22 => 
            array (
                'id' => '23',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Kosong',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2095',
            ),
            23 => 
            array (
                'id' => '24',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Mitra Makmur Bagya',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2096',
            ),
            24 => 
            array (
                'id' => '25',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Ciputra Nugraha International',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2097',
            ),
            25 => 
            array (
                'id' => '26',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Kosong',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2098',
            ),
            26 => 
            array (
                'id' => '27',
                'city_id' => NULL,
                'code' => 'I15',
                'name' => 'PT. PANASIA GRIYA MEKARASRI',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2099',
            ),
            27 => 
            array (
                'id' => '28',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Central International Property',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2100',
            ),
            28 => 
            array (
                'id' => '29',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO CITRALAND PALU',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '2101',
            ),
            29 => 
            array (
                'id' => '30',
                'city_id' => NULL,
                'code' => 'X01',
                'name' => 'PT. CIPUTRA INTERNASIONAL MDN',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3122',
            ),
            30 => 
            array (
                'id' => '31',
                'city_id' => NULL,
                'code' => 'X02',
                'name' => 'PT.CIPUTRA INTERNASIONAL ESC',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3124',
            ),
            31 => 
            array (
                'id' => '32',
                'city_id' => NULL,
                'code' => 'X03',
                'name' => 'PT.CIPUTRA INTERNASIONAL DK',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3125',
            ),
            32 => 
            array (
                'id' => '33',
                'city_id' => NULL,
                'code' => 'X04',
                'name' => 'PT.CIPUTRA BANGUN SELARAS',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3126',
            ),
            33 => 
            array (
                'id' => '34',
                'city_id' => NULL,
                'code' => 'X05',
                'name' => 'JO CIPUTRA KARYA PANCASAKTI NUGRAHA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3139',
            ),
            34 => 
            array (
                'id' => '35',
                'city_id' => NULL,
                'code' => 'X07',
                'name' => 'PT.CIPUTRA KPSN',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3140',
            ),
            35 => 
            array (
                'id' => '36',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Panasia Griya Mekarasri',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3141',
            ),
            36 => 
            array (
                'id' => '37',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. ANEKAINDAH MITRAPERKASA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3142',
            ),
            37 => 
            array (
                'id' => '38',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT CIPUTRA INTERNASIONAL MANADO',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3150',
            ),
            38 => 
            array (
                'id' => '39',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT Citra Grand Khatulistiwa',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3152',
            ),
            39 => 
            array (
                'id' => '40',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'CIPUTRA INTERNATIONAL',
                'address' => '',
                'npwp' => '',
                'phone' => '',
                'rekening' => '',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3157',
            ),
            40 => 
            array (
                'id' => '41',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT Ciputra Nusantara',
                'address' => '',
                'npwp' => '',
                'phone' => '',
                'rekening' => '',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3159',
            ),
            41 => 
            array (
                'id' => '42',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT Cipglobal megahkarya',
                'address' => '',
                'npwp' => '',
                'phone' => '',
                'rekening' => '',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3160',
            ),
            42 => 
            array (
                'id' => '43',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT Ciputra Internasional',
                'address' => '',
                'npwp' => '',
                'phone' => '',
                'rekening' => '',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3161',
            ),
            43 => 
            array (
                'id' => '44',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'Ciputra Yasmin',
                'address' => '',
                'npwp' => '',
                'phone' => '',
                'rekening' => '',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3162',
            ),
            44 => 
            array (
                'id' => '45',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT Citra Tirta Surabaya',
                'address' => '',
                'npwp' => '',
                'phone' => '',
                'rekening' => '',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3163',
            ),
            45 => 
            array (
                'id' => '46',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO CIPUTRA YASMIN BUMI ASRI',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3167',
            ),
            46 => 
            array (
                'id' => '47',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'CIPUTRA TALLASA JO',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3168',
            ),
            47 => 
            array (
                'id' => '48',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. CIPUTRA SYMPHONY',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3172',
            ),
            48 => 
            array (
                'id' => '49',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. CIPUTRA ABADI KARYA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3173',
            ),
            49 => 
            array (
                'id' => '50',
                'city_id' => NULL,
                'code' => 'XXXX',
                'name' => 'PT. CAHAYA FAJAR ABADITAMA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3190',
            ),
            50 => 
            array (
                'id' => '51',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO Ciputra Mutiara Cemerlang Abadi',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3192',
            ),
            51 => 
            array (
                'id' => '52',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. CIPUTRA INTERNASIONAL',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3193',
            ),
            52 => 
            array (
                'id' => '53',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO CIPUTRA KARYA UTAMA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3194',
            ),
            53 => 
            array (
                'id' => '54',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. CIPUTRA DEVELOPMENT TBK.',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3195',
            ),
            54 => 
            array (
                'id' => '55',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO Ciputra Sunindo Property',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3196',
            ),
            55 => 
            array (
                'id' => '56',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. CIPUTRA ABDI PERSADA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3197',
            ),
            56 => 
            array (
                'id' => '57',
                'city_id' => NULL,
                'code' => 'ACK',
                'name' => 'PT ARDAYA CIPTA KARSA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3198',
            ),
            57 => 
            array (
                'id' => '58',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Ciputra Inti Pratama',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3199',
            ),
            58 => 
            array (
                'id' => '59',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. Karya Utama Bumi',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3200',
            ),
            59 => 
            array (
                'id' => '60',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO. Ciputra Graha Terasama',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3201',
            ),
            60 => 
            array (
                'id' => '61',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO Sunindo Graha Utama',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '3202',
            ),
            61 => 
            array (
                'id' => '62',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO CITRALAND MANADO',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:49.000',
                'updated_at' => '2018-10-18 21:45:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '4219',
            ),
            62 => 
            array (
                'id' => '63',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. GRIYA MEKARASRI',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '4221',
            ),
            63 => 
            array (
                'id' => '64',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO Ciputra Sunindo Prima Utama',
                'address' => 'Jl. Laksda Adi Sucipto km.7, Yogyakarta',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '4222',
            ),
            64 => 
            array (
                'id' => '65',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. TAMAN DAYU',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '4224',
            ),
            65 => 
            array (
                'id' => '66',
                'city_id' => NULL,
                'code' => 'XXX',
            'name' => 'JO Ciputra Surya Sidoarjo Permai (JOCSSP)',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '4228',
            ),
            66 => 
            array (
                'id' => '67',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO CIPUTRA KARYA MAKMUR',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '4229',
            ),
            67 => 
            array (
                'id' => '68',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. TUMBUHSEMANGAT NIAGACEMERLANG',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '5233',
            ),
            68 => 
            array (
                'id' => '69',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'PT. GRAHA PELITA INDAH',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '5238',
            ),
            69 => 
            array (
                'id' => '70',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO Ciputra Mentari Propertindo',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '6240',
            ),
            70 => 
            array (
                'id' => '71',
                'city_id' => NULL,
                'code' => 'XXX',
                'name' => 'JO CIPUTRA KARYA PANCASAKTI NUSANTARA',
                'address' => 'NULL',
                'npwp' => 'NULL',
                'phone' => 'NULL',
                'rekening' => 'NULL',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-18 21:45:50.000',
                'updated_at' => '2018-10-18 21:45:50.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'pt_id' => '6244',
            ),
        ));
        
        
    }
}