<?php

use Illuminate\Database\Seeder;

class VosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vos')->delete();
        
        \DB::table('vos')->insert(array (
            0 => 
            array (
                'id' => '1',
                'suratinstruksi_id' => '1',
                'suratinstruksi_unit_id' => '1',
                'no' => 'Add-01-041/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:47.000',
                'updated_at' => '2018-10-25 01:39:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            1 => 
            array (
                'id' => '2',
                'suratinstruksi_id' => '2',
                'suratinstruksi_unit_id' => '2',
                'no' => 'Add.01-002/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:47.000',
                'updated_at' => '2018-10-25 01:39:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            2 => 
            array (
                'id' => '3',
                'suratinstruksi_id' => '3',
                'suratinstruksi_unit_id' => '3',
                'no' => 'Add.01-002/18',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:47.000',
                'updated_at' => '2018-10-25 01:39:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            3 => 
            array (
                'id' => '4',
                'suratinstruksi_id' => '4',
                'suratinstruksi_unit_id' => '4',
                'no' => 'Add.01-023/18',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:47.000',
                'updated_at' => '2018-10-25 01:39:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            4 => 
            array (
                'id' => '5',
                'suratinstruksi_id' => '5',
                'suratinstruksi_unit_id' => '5',
                'no' => 'Add.01-079/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            5 => 
            array (
                'id' => '6',
                'suratinstruksi_id' => '6',
                'suratinstruksi_unit_id' => '6',
                'no' => 'VO.001-022/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            6 => 
            array (
                'id' => '7',
                'suratinstruksi_id' => '7',
                'suratinstruksi_unit_id' => '7',
                'no' => 'VO.01-012/18',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            7 => 
            array (
                'id' => '8',
                'suratinstruksi_id' => '8',
                'suratinstruksi_unit_id' => '8',
                'no' => 'VO.01-014/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            8 => 
            array (
                'id' => '9',
                'suratinstruksi_id' => '9',
                'suratinstruksi_unit_id' => '9',
                'no' => 'VO.01-018/18',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            9 => 
            array (
                'id' => '10',
                'suratinstruksi_id' => '10',
                'suratinstruksi_unit_id' => '10',
                'no' => 'VO.01-020/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            10 => 
            array (
                'id' => '11',
                'suratinstruksi_id' => '11',
                'suratinstruksi_unit_id' => '11',
                'no' => 'VO.01-021/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            11 => 
            array (
                'id' => '12',
                'suratinstruksi_id' => '12',
                'suratinstruksi_unit_id' => '12',
                'no' => 'VO.01-026/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            12 => 
            array (
                'id' => '13',
                'suratinstruksi_id' => '13',
                'suratinstruksi_unit_id' => '13',
                'no' => 'VO.01-051/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            13 => 
            array (
                'id' => '14',
                'suratinstruksi_id' => '14',
                'suratinstruksi_unit_id' => '14',
                'no' => 'VO.01-052/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:48.000',
                'updated_at' => '2018-10-25 01:39:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            14 => 
            array (
                'id' => '15',
                'suratinstruksi_id' => '15',
                'suratinstruksi_unit_id' => '15',
                'no' => 'VO.01-054/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:49.000',
                'updated_at' => '2018-10-25 01:39:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            15 => 
            array (
                'id' => '16',
                'suratinstruksi_id' => '16',
                'suratinstruksi_unit_id' => '16',
                'no' => 'VO.01-064/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:49.000',
                'updated_at' => '2018-10-25 01:39:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            16 => 
            array (
                'id' => '17',
                'suratinstruksi_id' => '17',
                'suratinstruksi_unit_id' => '17',
                'no' => 'VO.01-071/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:49.000',
                'updated_at' => '2018-10-25 01:39:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            17 => 
            array (
                'id' => '18',
                'suratinstruksi_id' => '18',
                'suratinstruksi_unit_id' => '18',
                'no' => 'VO.01-075/17',
                'date' => '2018-10-25',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 01:39:49.000',
                'updated_at' => '2018-10-25 01:39:49.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            18 => 
            array (
                'id' => '19',
                'suratinstruksi_id' => '19',
                'suratinstruksi_unit_id' => '19',
                'no' => '',
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:30:16.000',
                'updated_at' => '2018-10-27 05:30:16.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            19 => 
            array (
                'id' => '20',
                'suratinstruksi_id' => '21',
                'suratinstruksi_unit_id' => '21',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:44.000',
                'updated_at' => '2018-10-27 05:33:44.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            20 => 
            array (
                'id' => '21',
                'suratinstruksi_id' => '22',
                'suratinstruksi_unit_id' => '22',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:44.000',
                'updated_at' => '2018-10-27 05:33:44.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            21 => 
            array (
                'id' => '22',
                'suratinstruksi_id' => '23',
                'suratinstruksi_unit_id' => '23',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:44.000',
                'updated_at' => '2018-10-27 05:33:44.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            22 => 
            array (
                'id' => '23',
                'suratinstruksi_id' => '24',
                'suratinstruksi_unit_id' => '24',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            23 => 
            array (
                'id' => '24',
                'suratinstruksi_id' => '25',
                'suratinstruksi_unit_id' => '25',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            24 => 
            array (
                'id' => '25',
                'suratinstruksi_id' => '26',
                'suratinstruksi_unit_id' => '26',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            25 => 
            array (
                'id' => '26',
                'suratinstruksi_id' => '27',
                'suratinstruksi_unit_id' => '27',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            26 => 
            array (
                'id' => '27',
                'suratinstruksi_id' => '28',
                'suratinstruksi_unit_id' => '28',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            27 => 
            array (
                'id' => '28',
                'suratinstruksi_id' => '29',
                'suratinstruksi_unit_id' => '29',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            28 => 
            array (
                'id' => '29',
                'suratinstruksi_id' => '30',
                'suratinstruksi_unit_id' => '30',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            29 => 
            array (
                'id' => '30',
                'suratinstruksi_id' => '31',
                'suratinstruksi_unit_id' => '31',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            30 => 
            array (
                'id' => '31',
                'suratinstruksi_id' => '32',
                'suratinstruksi_unit_id' => '32',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:45.000',
                'updated_at' => '2018-10-27 05:33:45.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            31 => 
            array (
                'id' => '32',
                'suratinstruksi_id' => '33',
                'suratinstruksi_unit_id' => '33',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:46.000',
                'updated_at' => '2018-10-27 05:33:46.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            32 => 
            array (
                'id' => '33',
                'suratinstruksi_id' => '34',
                'suratinstruksi_unit_id' => '34',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:46.000',
                'updated_at' => '2018-10-27 05:33:46.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            33 => 
            array (
                'id' => '34',
                'suratinstruksi_id' => '35',
                'suratinstruksi_unit_id' => '35',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:46.000',
                'updated_at' => '2018-10-27 05:33:46.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            34 => 
            array (
                'id' => '35',
                'suratinstruksi_id' => '36',
                'suratinstruksi_unit_id' => '36',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:46.000',
                'updated_at' => '2018-10-27 05:33:46.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            35 => 
            array (
                'id' => '36',
                'suratinstruksi_id' => '37',
                'suratinstruksi_unit_id' => '37',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:46.000',
                'updated_at' => '2018-10-27 05:33:46.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            36 => 
            array (
                'id' => '37',
                'suratinstruksi_id' => '38',
                'suratinstruksi_unit_id' => '38',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:46.000',
                'updated_at' => '2018-10-27 05:33:46.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            37 => 
            array (
                'id' => '38',
                'suratinstruksi_id' => '39',
                'suratinstruksi_unit_id' => '39',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            38 => 
            array (
                'id' => '39',
                'suratinstruksi_id' => '40',
                'suratinstruksi_unit_id' => '40',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            39 => 
            array (
                'id' => '40',
                'suratinstruksi_id' => '41',
                'suratinstruksi_unit_id' => '41',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            40 => 
            array (
                'id' => '41',
                'suratinstruksi_id' => '42',
                'suratinstruksi_unit_id' => '42',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            41 => 
            array (
                'id' => '42',
                'suratinstruksi_id' => '43',
                'suratinstruksi_unit_id' => '43',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            42 => 
            array (
                'id' => '43',
                'suratinstruksi_id' => '44',
                'suratinstruksi_unit_id' => '44',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            43 => 
            array (
                'id' => '44',
                'suratinstruksi_id' => '45',
                'suratinstruksi_unit_id' => '45',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            44 => 
            array (
                'id' => '45',
                'suratinstruksi_id' => '46',
                'suratinstruksi_unit_id' => '46',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:47.000',
                'updated_at' => '2018-10-27 05:33:47.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            45 => 
            array (
                'id' => '46',
                'suratinstruksi_id' => '47',
                'suratinstruksi_unit_id' => '47',
                'no' => NULL,
                'date' => '2018-10-27',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-27 05:33:48.000',
                'updated_at' => '2018-10-27 05:33:48.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            46 => 
            array (
                'id' => '47',
                'suratinstruksi_id' => '48',
                'suratinstruksi_unit_id' => '48',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:18.000',
                'updated_at' => '2018-10-28 21:36:18.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            47 => 
            array (
                'id' => '48',
                'suratinstruksi_id' => '49',
                'suratinstruksi_unit_id' => '49',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:18.000',
                'updated_at' => '2018-10-28 21:36:18.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            48 => 
            array (
                'id' => '49',
                'suratinstruksi_id' => '50',
                'suratinstruksi_unit_id' => '50',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:18.000',
                'updated_at' => '2018-10-28 21:36:18.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            49 => 
            array (
                'id' => '50',
                'suratinstruksi_id' => '51',
                'suratinstruksi_unit_id' => '51',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:18.000',
                'updated_at' => '2018-10-28 21:36:18.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            50 => 
            array (
                'id' => '51',
                'suratinstruksi_id' => '52',
                'suratinstruksi_unit_id' => '52',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            51 => 
            array (
                'id' => '52',
                'suratinstruksi_id' => '53',
                'suratinstruksi_unit_id' => '53',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            52 => 
            array (
                'id' => '53',
                'suratinstruksi_id' => '54',
                'suratinstruksi_unit_id' => '54',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            53 => 
            array (
                'id' => '54',
                'suratinstruksi_id' => '55',
                'suratinstruksi_unit_id' => '55',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            54 => 
            array (
                'id' => '55',
                'suratinstruksi_id' => '56',
                'suratinstruksi_unit_id' => '56',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            55 => 
            array (
                'id' => '56',
                'suratinstruksi_id' => '57',
                'suratinstruksi_unit_id' => '57',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            56 => 
            array (
                'id' => '57',
                'suratinstruksi_id' => '58',
                'suratinstruksi_unit_id' => '58',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            57 => 
            array (
                'id' => '58',
                'suratinstruksi_id' => '59',
                'suratinstruksi_unit_id' => '59',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:19.000',
                'updated_at' => '2018-10-28 21:36:19.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            58 => 
            array (
                'id' => '59',
                'suratinstruksi_id' => '60',
                'suratinstruksi_unit_id' => '60',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            59 => 
            array (
                'id' => '60',
                'suratinstruksi_id' => '61',
                'suratinstruksi_unit_id' => '61',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            60 => 
            array (
                'id' => '61',
                'suratinstruksi_id' => '62',
                'suratinstruksi_unit_id' => '62',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            61 => 
            array (
                'id' => '62',
                'suratinstruksi_id' => '63',
                'suratinstruksi_unit_id' => '63',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            62 => 
            array (
                'id' => '63',
                'suratinstruksi_id' => '64',
                'suratinstruksi_unit_id' => '64',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            63 => 
            array (
                'id' => '64',
                'suratinstruksi_id' => '65',
                'suratinstruksi_unit_id' => '65',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            64 => 
            array (
                'id' => '65',
                'suratinstruksi_id' => '66',
                'suratinstruksi_unit_id' => '66',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:20.000',
                'updated_at' => '2018-10-28 21:36:20.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            65 => 
            array (
                'id' => '66',
                'suratinstruksi_id' => '67',
                'suratinstruksi_unit_id' => '67',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            66 => 
            array (
                'id' => '67',
                'suratinstruksi_id' => '68',
                'suratinstruksi_unit_id' => '68',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            67 => 
            array (
                'id' => '68',
                'suratinstruksi_id' => '69',
                'suratinstruksi_unit_id' => '69',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            68 => 
            array (
                'id' => '69',
                'suratinstruksi_id' => '70',
                'suratinstruksi_unit_id' => '70',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            69 => 
            array (
                'id' => '70',
                'suratinstruksi_id' => '71',
                'suratinstruksi_unit_id' => '71',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            70 => 
            array (
                'id' => '71',
                'suratinstruksi_id' => '72',
                'suratinstruksi_unit_id' => '72',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            71 => 
            array (
                'id' => '72',
                'suratinstruksi_id' => '73',
                'suratinstruksi_unit_id' => '73',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            72 => 
            array (
                'id' => '73',
                'suratinstruksi_id' => '74',
                'suratinstruksi_unit_id' => '74',
                'no' => NULL,
                'date' => '2018-10-29',
                'urutan' => NULL,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-28 21:36:21.000',
                'updated_at' => '2018-10-28 21:36:21.000',
                'deleted_at' => NULL,
                'created_by' => '1',
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
        ));
        
        
    }
}