<?php

use Illuminate\Database\Seeder;

class BudgetTahunansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('budget_tahunans')->delete();
        
        \DB::table('budget_tahunans')->insert(array (
            0 => 
            array (
                'id' => 500,
                'budget_id' => 37,
                'parent_id' => NULL,
                'no' => '0028/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'Budget Fas Kot, Relokasi Pipa Gas PT.Pasundan',
                'created_at' => '2018-12-20 10:16:36',
                'updated_at' => '2018-12-20 10:16:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            1 => 
            array (
                'id' => 501,
                'budget_id' => 87,
                'parent_id' => NULL,
                'no' => '0030/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => NULL,
                'created_at' => '2018-12-21 03:21:30',
                'updated_at' => '2018-12-21 03:21:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            2 => 
            array (
                'id' => 502,
                'budget_id' => 37,
                'parent_id' => NULL,
                'no' => '0031/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'merevisi item budget yg lain belum dimasukkan',
                'created_at' => '2018-12-21 03:23:05',
                'updated_at' => '2018-12-21 03:23:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            3 => 
            array (
                'id' => 503,
                'budget_id' => 98,
                'parent_id' => NULL,
                'no' => '0033/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'merevisi item pek yg belum dimasukkan',
                'created_at' => '2018-12-21 03:59:36',
                'updated_at' => '2018-12-21 03:59:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            4 => 
            array (
                'id' => 504,
                'budget_id' => 52,
                'parent_id' => NULL,
                'no' => '0034/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'budget defcost cluster CC',
                'created_at' => '2018-12-21 04:13:04',
                'updated_at' => '2018-12-21 04:13:04',
                'deleted_at' => '2019-01-08 00:00:00',
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            5 => 
            array (
                'id' => 505,
                'budget_id' => 50,
                'parent_id' => NULL,
                'no' => '0039/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => NULL,
                'created_at' => '2018-12-27 04:07:33',
                'updated_at' => '2018-12-27 04:07:33',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            6 => 
            array (
                'id' => 506,
                'budget_id' => 74,
                'parent_id' => NULL,
                'no' => '0043/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'Pembangunan 5 unit rumah, tipe 96=3 unit, tipe 68=2unit',
                'created_at' => '2018-12-28 03:39:12',
                'updated_at' => '2018-12-28 03:39:12',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            7 => 
            array (
                'id' => 507,
                'budget_id' => 97,
                'parent_id' => NULL,
                'no' => '0044/BDG-T/CD/XII/2018/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'Con cost',
                'created_at' => '2018-12-28 10:35:06',
                'updated_at' => '2018-12-28 10:35:06',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            8 => 
            array (
                'id' => 508,
                'budget_id' => 5222222,
                'parent_id' => NULL,
                'no' => '0046/BDG-T/CD/I/2019/H/I01',
                'tahun_anggaran' => '2018',
                'description' => NULL,
                'created_at' => '2019-01-08 07:18:30',
                'updated_at' => '2019-01-08 07:18:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            9 => 
            array (
                'id' => 509,
                'budget_id' => 114,
                'parent_id' => NULL,
                'no' => '0056/BDG-T/CD/I/2019/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'DC',
                'created_at' => '2019-01-09 03:07:23',
                'updated_at' => '2019-01-09 03:07:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            10 => 
            array (
                'id' => 510,
                'budget_id' => 10777,
                'parent_id' => NULL,
                'no' => '0055/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2018',
                'description' => 'Budget Tahunan per 2019 - 8 Januari 2019',
                'created_at' => '2019-01-09 03:23:54',
                'updated_at' => '2019-01-09 03:23:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            11 => 
            array (
                'id' => 512,
                'budget_id' => 99,
                'parent_id' => NULL,
                'no' => '0057/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'budget tahunan 2019',
                'created_at' => '2019-01-09 03:28:23',
                'updated_at' => '2019-01-09 03:28:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            12 => 
            array (
                'id' => 513,
                'budget_id' => 115,
                'parent_id' => NULL,
                'no' => '0058/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => NULL,
                'created_at' => '2019-01-09 04:24:08',
                'updated_at' => '2019-01-09 06:51:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            13 => 
            array (
                'id' => 514,
                'budget_id' => 107,
                'parent_id' => NULL,
                'no' => '0059/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => NULL,
                'created_at' => '2019-01-09 04:36:25',
                'updated_at' => '2019-01-09 06:22:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            14 => 
            array (
                'id' => 515,
                'budget_id' => 104,
                'parent_id' => NULL,
                'no' => '0060/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => NULL,
                'created_at' => '2019-01-09 04:49:47',
                'updated_at' => '2019-01-09 06:07:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            15 => 
            array (
                'id' => 516,
                'budget_id' => 111,
                'parent_id' => NULL,
                'no' => '0061/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'Budget Tahunan 2019 per 9 Januari 2019',
                'created_at' => '2019-01-09 05:59:31',
                'updated_at' => '2019-01-09 05:59:31',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            16 => 
            array (
                'id' => 517,
                'budget_id' => 96,
                'parent_id' => NULL,
                'no' => '0062/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'budget tahunan per 9 januari 2019',
                'created_at' => '2019-01-09 06:05:20',
                'updated_at' => '2019-01-09 06:05:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            17 => 
            array (
                'id' => 518,
                'budget_id' => 113,
                'parent_id' => NULL,
                'no' => '0063/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'budget tahunan per 9 januari 2019',
                'created_at' => '2019-01-09 06:08:53',
                'updated_at' => '2019-01-09 06:08:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            18 => 
            array (
                'id' => 519,
                'budget_id' => 110,
                'parent_id' => NULL,
                'no' => '0064/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'budget tahunan per 9 januari 2019',
                'created_at' => '2019-01-09 07:23:04',
                'updated_at' => '2019-01-09 07:23:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            19 => 
            array (
                'id' => 520,
                'budget_id' => 112,
                'parent_id' => NULL,
                'no' => '0065/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'budget tahunan per 9 januari 2019',
                'created_at' => '2019-01-09 07:37:01',
                'updated_at' => '2019-01-09 07:37:01',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            20 => 
            array (
                'id' => 521,
                'budget_id' => 108,
                'parent_id' => NULL,
                'no' => '0066/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'budget tahunan per 9 januari 2019',
                'created_at' => '2019-01-09 07:54:20',
                'updated_at' => '2019-01-09 07:54:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            21 => 
            array (
                'id' => 522,
                'budget_id' => 877,
                'parent_id' => NULL,
                'no' => '0059/BDG-T/CD/I/2019/H/I01',
                'tahun_anggaran' => '2019',
                'description' => NULL,
                'created_at' => '2019-01-16 09:00:30',
                'updated_at' => '2019-01-16 09:00:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            22 => 
            array (
                'id' => 523,
                'budget_id' => 106,
                'parent_id' => NULL,
                'no' => '0068/BDG-T/CD/I/2019/XXX/XXX',
                'tahun_anggaran' => '2019',
                'description' => 'Budget Ruko F',
                'created_at' => '2019-01-16 11:39:50',
                'updated_at' => '2019-01-16 11:39:50',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            23 => 
            array (
                'id' => 524,
                'budget_id' => 117,
                'parent_id' => NULL,
                'no' => '0061/BDG-T/CD/I/2019/H/I01',
                'tahun_anggaran' => '2019',
                'description' => 'budget gabungan',
                'created_at' => '2019-01-17 11:07:05',
                'updated_at' => '2019-01-17 11:07:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
        ));
        
        
    }
}