<?php

use Illuminate\Database\Seeder;

class BudgetsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('budgets')->delete();
        
        \DB::table('budgets')->insert(array (
            0 => 
            array (
                'id' => 11,
                'pt_id' => 24,
                'department_id' => 2,
                'project_id' => 66,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0011/BDG/CD/X/2018/XXX/XXX',
                'start_date' => '2018-01-01',
                'end_date' => '2018-12-31',
                'description' => 'Migration from Project based export at 18 Oct 2018',
                'created_at' => '2018-10-26 01:08:59',
                'updated_at' => '2018-10-26 01:08:59',
                'deleted_at' => '2018-10-28 17:00:00',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            1 => 
            array (
                'id' => 13,
                'pt_id' => 24,
                'department_id' => 2,
                'project_id' => 66,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0012/BDG/CD/X/2018/XXX/XXX',
                'start_date' => '2018-01-01',
                'end_date' => '2018-12-31',
                'description' => 'Migration from Project based export at 18 Oct 2018',
                'created_at' => '2018-10-28 22:40:52',
                'updated_at' => '2018-10-28 22:40:52',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            2 => 
            array (
                'id' => 19,
                'pt_id' => 1,
                'department_id' => 2,
                'project_id' => 82,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0013/BDG/CD/XI/2018/PTD/D01',
                'start_date' => '2018-11-09',
                'end_date' => '2027-11-09',
                'description' => 'Fasilitas Kota',
                'created_at' => '2018-11-09 06:35:30',
                'updated_at' => '2018-11-09 06:35:30',
                'deleted_at' => NULL,
                'created_by' => 32,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            3 => 
            array (
                'id' => 20,
                'pt_id' => 1,
                'department_id' => 2,
                'project_id' => 82,
                'parent_id' => NULL,
                'project_kawasan_id' => 13,
                'no' => '0014/BDG/CD/XI/2018/PTD/D01',
                'start_date' => '2018-11-09',
                'end_date' => '2027-11-09',
                'description' => 'Kawasan Nusa Dua',
                'created_at' => '2018-11-09 08:32:44',
                'updated_at' => '2018-11-09 08:32:44',
                'deleted_at' => NULL,
                'created_by' => 32,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            4 => 
            array (
                'id' => 21,
                'pt_id' => 1,
                'department_id' => 2,
                'project_id' => 82,
                'parent_id' => NULL,
                'project_kawasan_id' => 14,
                'no' => '0015/BDG/CD/XI/2018/PTD/D01',
                'start_date' => '2018-11-09',
                'end_date' => '2027-11-09',
                'description' => 'Kawasan Branwood',
                'created_at' => '2018-11-09 08:39:21',
                'updated_at' => '2018-11-09 08:39:21',
                'deleted_at' => NULL,
                'created_by' => 32,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            5 => 
            array (
                'id' => 24,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0016/BDG/CD/XI/2018/XXX/XXX',
                'start_date' => '2018-11-16',
                'end_date' => '2018-11-30',
                'description' => 'Faskot',
                'created_at' => '2018-11-16 17:07:11',
                'updated_at' => '2018-11-16 17:07:11',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            6 => 
            array (
                'id' => 25,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => NULL,
                'project_kawasan_id' => 40,
                'no' => '0017/BDG/CD/XI/2018/XXX/XXX',
                'start_date' => '2018-11-16',
                'end_date' => '2018-11-30',
                'description' => 'kawasan',
                'created_at' => '2018-11-16 17:12:00',
                'updated_at' => '2018-11-19 15:29:04',
                'deleted_at' => '2018-11-19 15:29:04',
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            7 => 
            array (
                'id' => 26,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => NULL,
                'project_kawasan_id' => 41,
                'no' => '0018/BDG/CD/XI/2018/XXX/XXX',
                'start_date' => '2018-11-16',
                'end_date' => '2018-11-30',
                'description' => 'kawasan',
                'created_at' => '2018-11-16 17:25:49',
                'updated_at' => '2018-11-19 16:02:16',
                'deleted_at' => '2018-11-19 16:02:16',
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            8 => 
            array (
                'id' => 27,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => 25,
                'project_kawasan_id' => 40,
                'no' => '0017/BDG/CD/XI/2018/XXX/XXX-R1',
                'start_date' => '2018-11-16',
                'end_date' => '2018-11-30',
                'description' => NULL,
                'created_at' => '2018-11-19 15:29:04',
                'updated_at' => '2018-11-19 15:29:04',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            9 => 
            array (
                'id' => 28,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => 26,
                'project_kawasan_id' => 41,
                'no' => '0018/BDG/CD/XI/2018/XXX/XXX-R1',
                'start_date' => '2018-11-16',
                'end_date' => '2018-11-30',
                'description' => NULL,
                'created_at' => '2018-11-19 16:02:16',
                'updated_at' => '2018-11-19 16:02:16',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            10 => 
            array (
                'id' => 31,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 50,
                'no' => '0023/BDG/CD/XII/2018/H/I01',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => 'Budget global untuk kawasan Clover Garden Blok CC',
                'created_at' => '2018-12-20 03:41:43',
                'updated_at' => '2019-01-08 03:44:21',
                'deleted_at' => '2019-01-08 03:44:21',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            11 => 
            array (
                'id' => 32,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 49,
                'no' => '0024/BDG/CD/XII/2018/H/I01',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => 'Budget cluster P ext 2',
                'created_at' => '2018-12-20 06:51:32',
                'updated_at' => '2019-01-08 02:36:28',
                'deleted_at' => '2019-01-08 02:36:28',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            12 => 
            array (
                'id' => 33,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0025/BDG/CD/XII/2018/XXX/XXX',
                'start_date' => '2018-12-20',
                'end_date' => '2018-12-20',
                'description' => NULL,
                'created_at' => '2018-12-20 07:06:37',
                'updated_at' => '2018-12-20 07:06:37',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            13 => 
            array (
                'id' => 34,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0026/BDG/CD/XII/2018/H/I01',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => 'Budget Fas-kot',
                'created_at' => '2018-12-20 08:50:10',
                'updated_at' => '2018-12-21 03:04:40',
                'deleted_at' => '2018-12-21 03:04:40',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            14 => 
            array (
                'id' => 35,
                'pt_id' => 27,
                'department_id' => 2,
                'project_id' => 61,
                'parent_id' => NULL,
                'project_kawasan_id' => 51,
                'no' => '0027/BDG/CD/XII/2018/I/I15',
                'start_date' => '2018-12-20',
                'end_date' => '2024-01-20',
                'description' => 'KAWASAN NEW LIVISTONA',
                'created_at' => '2018-12-20 09:02:12',
                'updated_at' => '2018-12-20 09:02:12',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            15 => 
            array (
                'id' => 36,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 34,
                'project_kawasan_id' => NULL,
                'no' => '0026/BDG/CD/XII/2018/H/I01-R1',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => NULL,
                'created_at' => '2018-12-21 03:04:40',
                'updated_at' => '2018-12-21 03:43:02',
                'deleted_at' => '2018-12-21 03:43:02',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            16 => 
            array (
                'id' => 37,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 36,
                'project_kawasan_id' => NULL,
                'no' => '0026/BDG/CD/XII/2018/H/I01-R1-R1',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => NULL,
                'created_at' => '2018-12-21 03:43:02',
                'updated_at' => '2019-01-08 05:11:12',
                'deleted_at' => '2019-01-08 05:11:12',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            17 => 
            array (
                'id' => 39,
                'pt_id' => 2,
                'department_id' => 2,
                'project_id' => 1,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0028/BDG/CD/XII/2018/D/D02',
                'start_date' => '2018-12-21',
                'end_date' => '2023-12-22',
                'description' => 'Budget Faskot PT Mitrakusuma  Erasemesta',
                'created_at' => '2018-12-21 06:32:25',
                'updated_at' => '2018-12-21 06:32:25',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            18 => 
            array (
                'id' => 40,
                'pt_id' => 2,
                'department_id' => 2,
                'project_id' => 1,
                'parent_id' => NULL,
                'project_kawasan_id' => 47,
                'no' => '0029/BDG/CD/XII/2018/D/D02',
                'start_date' => '2018-12-21',
                'end_date' => '2022-12-31',
                'description' => 'Budget devcost kawasan bukit orchid',
                'created_at' => '2018-12-21 07:45:25',
                'updated_at' => '2018-12-21 07:45:25',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            19 => 
            array (
                'id' => 41,
                'pt_id' => 2,
                'department_id' => 2,
                'project_id' => 1,
                'parent_id' => NULL,
                'project_kawasan_id' => 48,
                'no' => '0030/BDG/CD/XII/2018/D/D02',
                'start_date' => '2018-12-21',
                'end_date' => '2021-12-31',
                'description' => 'Budget kawasan ruko orchid boulevard',
                'created_at' => '2018-12-21 09:55:04',
                'updated_at' => '2018-12-21 09:55:04',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            20 => 
            array (
                'id' => 43,
                'pt_id' => 2,
                'department_id' => 2,
                'project_id' => 1,
                'parent_id' => NULL,
                'project_kawasan_id' => 46,
                'no' => '0031/BDG/CD/XII/2018/D/D02',
                'start_date' => '2018-12-26',
                'end_date' => '2021-12-31',
                'description' => 'Budget Bukit Sakura',
                'created_at' => '2018-12-26 04:07:03',
                'updated_at' => '2018-12-26 04:07:03',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            21 => 
            array (
                'id' => 44,
                'pt_id' => 68,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0032/BDG/CD/XII/2018/H/XXX',
                'start_date' => '2018-12-26',
                'end_date' => '2025-12-31',
                'description' => 'Asumsi Devcost Cikeas',
                'created_at' => '2018-12-26 04:53:18',
                'updated_at' => '2018-12-26 04:53:18',
                'deleted_at' => '2018-12-27 00:00:00',
                'created_by' => 48,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            22 => 
            array (
                'id' => 45,
                'pt_id' => 2,
                'department_id' => 2,
                'project_id' => 1,
                'parent_id' => NULL,
                'project_kawasan_id' => 45,
                'no' => '0033/BDG/CD/XII/2018/D/D02',
                'start_date' => '2018-12-26',
                'end_date' => '2021-12-31',
                'description' => 'Budget Development Cost Bukit Sakura',
                'created_at' => '2018-12-26 06:30:01',
                'updated_at' => '2018-12-26 06:30:01',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            23 => 
            array (
                'id' => 46,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 65,
                'no' => '0034/BDG/CD/XII/2018/H/I01',
                'start_date' => '2018-12-27',
                'end_date' => '2018-12-31',
                'description' => 'Budget global blok AA ext',
                'created_at' => '2018-12-27 10:18:11',
                'updated_at' => '2019-01-08 04:06:40',
                'deleted_at' => '2019-01-08 04:06:40',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            24 => 
            array (
                'id' => 47,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 66,
                'no' => '0035/BDG/CD/XII/2018/H/I01',
                'start_date' => '2018-12-27',
                'end_date' => '2025-12-31',
                'description' => 'Budget global blok BB',
                'created_at' => '2018-12-27 10:24:41',
                'updated_at' => '2019-01-08 04:19:05',
                'deleted_at' => '2019-01-08 04:19:05',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            25 => 
            array (
                'id' => 48,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 67,
                'no' => '0036/BDG/CD/XII/2018/H/I01',
                'start_date' => '2018-12-28',
                'end_date' => '2019-12-31',
                'description' => 'budget con cost 2019',
                'created_at' => '2018-12-28 01:56:38',
                'updated_at' => '2019-01-08 04:36:52',
                'deleted_at' => '2019-01-08 04:36:52',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            26 => 
            array (
                'id' => 50,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 32,
                'project_kawasan_id' => 49,
                'no' => '0024/BDG/CD/XII/2018/H/I01-R1',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => 'budget revisi per 8 Jan 2019',
                'created_at' => '2019-01-08 02:36:28',
                'updated_at' => '2019-01-08 02:36:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            27 => 
            array (
                'id' => 52,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 31,
                'project_kawasan_id' => 50,
                'no' => '0023/BDG/CD/XII/2018/H/I01-R1',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => 'revisi budget per 8Jan2019',
                'created_at' => '2019-01-08 03:44:21',
                'updated_at' => '2019-01-08 03:44:21',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            28 => 
            array (
                'id' => 74,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 46,
                'project_kawasan_id' => 65,
                'no' => '0034/BDG/CD/XII/2018/H/I01-R1',
                'start_date' => '2018-12-27',
                'end_date' => '2018-12-31',
                'description' => 'revisi budget per8Jan2019',
                'created_at' => '2019-01-08 04:06:40',
                'updated_at' => '2019-01-08 04:06:40',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            29 => 
            array (
                'id' => 75,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 70,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2018-08-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:13',
                'updated_at' => '2018-10-01 13:05:35',
                'deleted_at' => '2018-10-01 13:05:35',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            30 => 
            array (
                'id' => 76,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 71,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:15',
                'updated_at' => '2018-10-01 17:15:27',
                'deleted_at' => '2018-10-01 17:15:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            31 => 
            array (
                'id' => 77,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 72,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:16',
                'updated_at' => '2018-10-02 11:24:52',
                'deleted_at' => '2018-10-02 11:24:52',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            32 => 
            array (
                'id' => 78,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 73,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:18',
                'updated_at' => '2018-10-02 09:20:53',
                'deleted_at' => '2018-10-02 09:20:53',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            33 => 
            array (
                'id' => 79,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 74,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:19',
                'updated_at' => '2018-10-02 09:56:33',
                'deleted_at' => '2018-10-02 09:56:33',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            34 => 
            array (
                'id' => 80,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 75,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:21',
                'updated_at' => '2018-10-02 12:10:14',
                'deleted_at' => '2018-10-02 12:10:14',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            35 => 
            array (
                'id' => 81,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 76,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:23',
                'updated_at' => '2018-10-02 12:24:26',
                'deleted_at' => '2018-10-02 12:24:26',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            36 => 
            array (
                'id' => 82,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 77,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:25',
                'updated_at' => '2018-07-13 08:35:25',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            37 => 
            array (
                'id' => 83,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 78,
                'no' => NULL,
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-07-13 08:35:26',
                'updated_at' => '2018-10-02 12:42:19',
                'deleted_at' => '2018-10-02 12:42:19',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            38 => 
            array (
                'id' => 85,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0036/BDG/CD/X/2018/CGCC/JGG',
                'start_date' => '2018-10-01',
                'end_date' => '2028-12-31',
                'description' => NULL,
                'created_at' => '2018-10-01 15:15:49',
                'updated_at' => '2019-01-08 08:40:32',
                'deleted_at' => '2019-01-08 08:40:32',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            39 => 
            array (
                'id' => 86,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => NULL,
                'project_kawasan_id' => 79,
                'no' => '0047/BDG/CD/X/2018/CGCC/CNI',
                'start_date' => '2018-10-01',
                'end_date' => '2028-12-31',
                'description' => NULL,
                'created_at' => '2018-10-02 14:20:04',
                'updated_at' => '2019-01-08 08:00:56',
                'deleted_at' => '2019-01-08 08:00:56',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            40 => 
            array (
                'id' => 87,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 47,
                'project_kawasan_id' => 66,
                'no' => '0035/BDG/CD/XII/2018/H/I01-R1',
                'start_date' => '2018-12-27',
                'end_date' => '2025-12-31',
                'description' => 'revisi budget per8Jan2019',
                'created_at' => '2019-01-08 04:19:05',
                'updated_at' => '2019-01-08 04:19:05',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            41 => 
            array (
                'id' => 88,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 10,
                'project_kawasan_id' => NULL,
                'no' => '0002/BDG-R/CD/VIII/2018/CBD/JGG',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-08-09 10:10:59',
                'updated_at' => '2018-08-09 10:10:59',
                'deleted_at' => '2018-10-02 07:00:00',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 0,
            ),
            42 => 
            array (
                'id' => 89,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 75,
                'project_kawasan_id' => 70,
                'no' => '-R1',
                'start_date' => '2020-01-01',
                'end_date' => '2025-12-31',
                'description' => NULL,
                'created_at' => '2018-10-01 13:05:35',
                'updated_at' => '2019-01-08 08:54:12',
                'deleted_at' => '2019-01-08 08:54:12',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            43 => 
            array (
                'id' => 90,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 76,
                'project_kawasan_id' => 71,
                'no' => '-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-01 17:15:27',
                'updated_at' => '2019-01-08 09:26:05',
                'deleted_at' => '2019-01-08 09:26:05',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            44 => 
            array (
                'id' => 91,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 81,
                'project_kawasan_id' => 76,
                'no' => '-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-01 18:13:01',
                'updated_at' => '2019-01-08 10:25:28',
                'deleted_at' => '2019-01-08 10:25:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            45 => 
            array (
                'id' => 92,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 78,
                'project_kawasan_id' => 73,
                'no' => '-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-02 09:20:53',
                'updated_at' => '2019-01-08 09:42:32',
                'deleted_at' => '2019-01-08 09:42:32',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            46 => 
            array (
                'id' => 93,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 79,
                'project_kawasan_id' => 74,
                'no' => '-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-02 09:56:33',
                'updated_at' => '2019-01-08 05:23:07',
                'deleted_at' => '2019-01-08 05:23:07',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            47 => 
            array (
                'id' => 94,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 77,
                'project_kawasan_id' => 72,
                'no' => '-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-02 11:24:52',
                'updated_at' => '2019-01-08 08:42:24',
                'deleted_at' => '2019-01-08 08:42:24',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            48 => 
            array (
                'id' => 95,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 80,
                'project_kawasan_id' => 75,
                'no' => '-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-02 12:10:14',
                'updated_at' => '2019-01-08 06:55:28',
                'deleted_at' => '2019-01-08 06:55:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            49 => 
            array (
                'id' => 96,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 6000,
                'parent_id' => 81,
                'project_kawasan_id' => 76,
                'no' => '-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2018-10-02 12:24:26',
                'updated_at' => '2018-10-02 12:24:26',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            50 => 
            array (
                'id' => 97,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 48,
                'project_kawasan_id' => 67,
                'no' => '0036/BDG/CD/XII/2018/H/I01-R1',
                'start_date' => '2018-12-28',
                'end_date' => '2019-12-31',
                'description' => 'revisi budget per 8Jan2019',
                'created_at' => '2019-01-08 04:36:52',
                'updated_at' => '2019-01-08 04:36:52',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            51 => 
            array (
                'id' => 98,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => 37,
                'project_kawasan_id' => NULL,
                'no' => '0026/BDG/CD/XII/2018/H/I01-R1-R1-R1',
                'start_date' => '2018-12-20',
                'end_date' => '2025-12-31',
                'description' => 'revisi budget per 8Jan2019',
                'created_at' => '2019-01-08 05:11:12',
                'updated_at' => '2019-01-08 05:11:12',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            52 => 
            array (
                'id' => 99,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 93,
                'project_kawasan_id' => 74,
                'no' => '-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => NULL,
                'created_at' => '2019-01-08 05:23:07',
                'updated_at' => '2019-01-09 03:56:55',
                'deleted_at' => '2019-01-09 03:56:55',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            53 => 
            array (
                'id' => 104,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 95,
                'project_kawasan_id' => 75,
                'no' => '-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => 'Revisi budget per 8 Januari 2019',
                'created_at' => '2019-01-08 06:55:28',
                'updated_at' => '2019-01-08 06:55:28',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            54 => 
            array (
                'id' => 106,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 86,
                'project_kawasan_id' => 79,
                'no' => '0047/BDG/CD/X/2018/CGCC/CNI-R2',
                'start_date' => '2018-10-01',
                'end_date' => '2028-12-31',
                'description' => 'Revisi Budget per 8 Januari 2019',
                'created_at' => '2019-01-08 08:00:56',
                'updated_at' => '2019-01-08 08:00:56',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            55 => 
            array (
                'id' => 107,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 85,
                'project_kawasan_id' => NULL,
                'no' => '0036/BDG/CD/X/2018/CGCC/JGG-R1',
                'start_date' => '2018-10-01',
                'end_date' => '2028-12-31',
                'description' => 'Revisi budget per 8 Januari 2019',
                'created_at' => '2019-01-08 08:40:32',
                'updated_at' => '2019-01-08 08:40:32',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            56 => 
            array (
                'id' => 108,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 94,
                'project_kawasan_id' => 72,
                'no' => '-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => 'Revisi Budget per 8 Januari 2019',
                'created_at' => '2019-01-08 08:42:24',
                'updated_at' => '2019-01-08 08:42:24',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            57 => 
            array (
                'id' => 109,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 6000,
                'parent_id' => 89,
                'project_kawasan_id' => 70,
                'no' => '-R1-R1',
                'start_date' => '2020-01-01',
                'end_date' => '2025-12-31',
                'description' => 'Budget revisi per 8 januari 2019',
                'created_at' => '2019-01-08 08:53:53',
                'updated_at' => '2019-01-08 08:53:53',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            58 => 
            array (
                'id' => 110,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 89,
                'project_kawasan_id' => 70,
                'no' => '-R1-R2',
                'start_date' => '2020-01-01',
                'end_date' => '2025-12-31',
                'description' => 'Budget revisi per 8 januari 2019',
                'created_at' => '2019-01-08 08:54:12',
                'updated_at' => '2019-01-08 08:54:12',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            59 => 
            array (
                'id' => 111,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 90,
                'project_kawasan_id' => 71,
                'no' => '-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => 'Revisi budget per 8 Januari 2019',
                'created_at' => '2019-01-08 09:26:05',
                'updated_at' => '2019-01-08 09:26:05',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            60 => 
            array (
                'id' => 112,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 92,
                'project_kawasan_id' => 73,
                'no' => '-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => 'revisi budget per 8 januari 2019',
                'created_at' => '2019-01-08 09:42:32',
                'updated_at' => '2019-01-08 09:42:32',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            61 => 
            array (
                'id' => 113,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 91,
                'project_kawasan_id' => 76,
                'no' => '-R1-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => 'Revisi budget per 8 Januari 2019',
                'created_at' => '2019-01-08 10:25:28',
                'updated_at' => '2019-01-08 10:25:28',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            62 => 
            array (
                'id' => 114,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 80,
                'no' => '0054/BDG/CD/I/2019/H/I01',
                'start_date' => '2019-01-09',
                'end_date' => '2020-01-01',
                'description' => 'dc and CC',
                'created_at' => '2019-01-09 02:36:36',
                'updated_at' => '2019-01-09 02:36:36',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            63 => 
            array (
                'id' => 115,
                'pt_id' => 25,
                'department_id' => 2,
                'project_id' => 60,
                'parent_id' => 99,
                'project_kawasan_id' => 74,
                'no' => '-R1-R1-R1',
                'start_date' => '2017-01-01',
                'end_date' => '2020-12-31',
                'description' => 'revisi budget per 9 januari 2019',
                'created_at' => '2019-01-09 03:56:55',
                'updated_at' => '2019-01-09 03:56:55',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            64 => 
            array (
                'id' => 116,
                'pt_id' => 48,
                'department_id' => 2,
                'project_id' => 9,
                'parent_id' => NULL,
                'project_kawasan_id' => NULL,
                'no' => '0056/BDG/CD/I/2019/XXX/XXX',
                'start_date' => '2019-01-16',
                'end_date' => '2019-01-31',
                'description' => NULL,
                'created_at' => '2019-01-16 04:16:08',
                'updated_at' => '2019-01-16 04:16:08',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
            65 => 
            array (
                'id' => 117,
                'pt_id' => 17,
                'department_id' => 2,
                'project_id' => 3,
                'parent_id' => NULL,
                'project_kawasan_id' => 81,
                'no' => '0057/BDG/CD/I/2019/H/I01',
                'start_date' => '2019-01-17',
                'end_date' => '2020-01-24',
                'description' => 'budget campur Blok F, AA, Pext, U, RC',
                'created_at' => '2019-01-17 11:04:11',
                'updated_at' => '2019-01-17 11:04:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status_active' => 1,
            ),
        ));
        
        
    }
}