<?php

use Illuminate\Database\Seeder;

class DepartmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('departments')->delete();
        
        \DB::table('departments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'CMS',
                'name' => 'ESTAT MANAGEMENT',
                'description' => 'ESTATE',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-08-01 10:36:44',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'CD',
                'name' => 'CONSTRUCTION & DEVELOPMENT',
                'description' => 'CONSTRUCTION & DEVELOPMENT',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'ENG',
                'name' => 'ENGINEERING',
                'description' => 'ENGINEERING',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'EXM',
                'name' => 'EXECUTIVE MANAGEMENT',
                'description' => 'EXECUTIVE MANAGEMENT',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'FAM',
                'name' => 'FAMILY CLUB',
                'description' => 'FAMILY CLUB',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'FA',
                'name' => 'FINANCE & ACCOUNTING',
                'description' => 'FINANCE & ACCOUNTING',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'FBV',
                'name' => 'FOOD & BEVERAGE',
                'description' => 'FOOD & BEVERAGE',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'FCT',
                'name' => 'FOOD COURT',
                'description' => 'FOOD COURT',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'GCM',
                'name' => 'GOLF COURCE MAINTENANCE',
                'description' => 'GOLF COURCE MAINTENANCE',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'GOP',
                'name' => 'GOLF OPERATION',
                'description' => 'GOLF OPERATION',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'HKH',
                'name' => 'HOUSE KEEPING & HOTEL',
                'description' => 'HOUSE KEEPING & HOTEL',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-07-03 22:05:57',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'HCM',
                'name' => 'HUMAN CAPITAL MANAGEMENT',
                'description' => 'HUMAN CAPITAL MANAGEMENT & GA',
                'created_at' => '2018-07-03 22:05:57',
                'updated_at' => '2018-10-04 09:01:19',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'ICT',
                'name' => 'ICT',
                'description' => 'ICT',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'LGL',
                'name' => 'LAND & LEGAL',
                'description' => 'LAND & LEGAL',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'LA',
                'name' => 'LAND AQUISITION',
                'description' => 'LAND AQUISITION',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'LSG',
                'name' => 'LEASING',
                'description' => 'LEASING',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'MKT',
                'name' => 'MARKETING',
                'description' => 'MARKETING',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'OPR',
                'name' => 'OPERATIONAL',
                'description' => 'OPERATIONAL',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'NET',
                'name' => 'NETWORKING',
                'description' => 'NETWORKING',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'PER',
                'name' => 'PERMIT',
                'description' => 'PERMIT',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'PD',
                'name' => 'PROJECT DEVELOPMENT',
                'description' => 'PROJECT DEVELOPMENT',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'PMA',
                'name' => 'PROJECT MANAGEMENT',
                'description' => 'PROJECT MANAGEMENT',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'PRM',
                'name' => 'PROMOTION',
                'description' => 'PROMOTION',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'SVC',
                'name' => 'SERVICE',
                'description' => 'SERVICE',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'TLT',
                'name' => 'TALENT DEVELOPMENT',
                'description' => 'TALENT DEVELOPMENT',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'TNT',
                'name' => 'TENANT DESIGN',
                'description' => 'TENANT DESIGN',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'TRN',
                'name' => 'TRAINING',
                'description' => 'TRAINING',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'WP',
                'name' => 'WATERPARK',
                'description' => 'WATERPARK',
                'created_at' => '2018-07-03 22:05:58',
                'updated_at' => '2018-07-03 22:05:58',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'ISS',
                'name' => 'CLEANING SERVICE',
                'description' => NULL,
                'created_at' => '2018-07-31 14:02:13',
                'updated_at' => '2018-07-31 14:02:13',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            29 => 
            array (
                'id' => 32,
                'code' => 'CM',
                'name' => 'CITY MANAGEMENT',
                'description' => 'SAMA SEPERTI ESTATE',
                'created_at' => '2018-10-04 09:02:39',
                'updated_at' => '2018-10-04 09:02:39',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
        ));
        
        
    }
}