<?php

use Illuminate\Database\Seeder;

class HppUpdatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hpp_updates')->delete();
        
        \DB::table('hpp_updates')->insert(array (
            0 => 
            array (
                'id' => 1,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '30679983290',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2018-12-20 09:32:10',
                'updated_at' => '2018-12-20 09:32:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 27241,
                'hpp_book' => '1126242.91',
                'luas_book_before' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '39635622690',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2018-12-21 03:20:10',
                'updated_at' => '2018-12-21 03:20:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 27241,
                'hpp_book' => '1454998.81',
                'luas_book_before' => '1126242.91',
            ),
            2 => 
            array (
                'id' => 3,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '29797871290',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2018-12-21 03:49:59',
                'updated_at' => '2018-12-21 03:49:59',
                'created_by' => 24,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 27241,
                'hpp_book' => '1093861.14',
                'luas_book_before' => '1454998.81',
            ),
            3 => 
            array (
                'id' => 4,
                'project_id' => 1,
                'pt_id' => NULL,
                'nilai_budget' => '78635665683',
                'luas_book' => '141584.00',
                'luas_erem' => NULL,
                'created_at' => '2018-12-28 03:35:23',
                'updated_at' => '2018-12-28 03:35:23',
                'created_by' => 24,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => NULL,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '22899399624',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => NULL,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'project_id' => 60,
                'pt_id' => NULL,
                'nilai_budget' => '191615209829.0',
                'luas_book' => '0.00',
                'luas_erem' => '0.00',
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 186849,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'project_id' => 60,
                'pt_id' => NULL,
                'nilai_budget' => '204201093335',
                'luas_book' => '0.00',
                'luas_erem' => '0.00',
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 186849,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'project_id' => 60,
                'pt_id' => NULL,
                'nilai_budget' => '204201093335',
                'luas_book' => '0.00',
                'luas_erem' => '0.00',
                'created_at' => '2019-01-15 04:08:11',
                'updated_at' => '2019-01-15 04:08:11',
                'created_by' => NULL,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 186849,
                'hpp_book' => '1092865.18',
                'luas_book_before' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '60535272241',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => NULL,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '60535272241',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2019-01-18 03:01:27',
                'updated_at' => '2019-01-18 03:01:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 84982,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '60535272241',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 90510,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'project_id' => 3,
                'pt_id' => NULL,
                'nilai_budget' => '67547077915',
                'luas_book' => '0.00',
                'luas_erem' => NULL,
                'created_at' => '2019-01-21 03:51:21',
                'updated_at' => '2019-01-21 03:51:21',
                'created_by' => 1,
                'updated_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'netto' => 90510,
                'hpp_book' => NULL,
                'luas_book_before' => NULL,
            ),
        ));
        
        
    }
}