<?php

use Illuminate\Database\Seeder;

class UnitTypeCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('unit_type_categories')->delete();
        
        \DB::table('unit_type_categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'unit_type_id' => 1,
                'category_project_id' => 4,
                'created_at' => '2018-12-17 08:31:13',
                'updated_at' => '2018-12-17 08:31:13',
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '1',
            ),
            1 => 
            array (
                'id' => 2,
                'unit_type_id' => 4,
                'category_project_id' => 5,
                'created_at' => '2018-12-21 08:57:07',
                'updated_at' => '2018-12-21 08:57:07',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            2 => 
            array (
                'id' => 3,
                'unit_type_id' => 5,
                'category_project_id' => 6,
                'created_at' => '2018-12-21 08:58:06',
                'updated_at' => '2018-12-21 08:58:06',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            3 => 
            array (
                'id' => 4,
                'unit_type_id' => 6,
                'category_project_id' => 7,
                'created_at' => '2018-12-21 08:58:45',
                'updated_at' => '2018-12-21 08:58:45',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            4 => 
            array (
                'id' => 5,
                'unit_type_id' => 7,
                'category_project_id' => 8,
                'created_at' => '2018-12-21 08:59:22',
                'updated_at' => '2018-12-21 08:59:22',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            5 => 
            array (
                'id' => 6,
                'unit_type_id' => 8,
                'category_project_id' => 9,
                'created_at' => '2018-12-21 08:59:57',
                'updated_at' => '2018-12-21 08:59:57',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            6 => 
            array (
                'id' => 7,
                'unit_type_id' => 10,
                'category_project_id' => 10,
                'created_at' => '2018-12-27 02:20:12',
                'updated_at' => '2018-12-27 02:20:12',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            7 => 
            array (
                'id' => 8,
                'unit_type_id' => 11,
                'category_project_id' => 11,
                'created_at' => '2018-12-27 02:23:11',
                'updated_at' => '2018-12-27 02:23:11',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            8 => 
            array (
                'id' => 9,
                'unit_type_id' => 12,
                'category_project_id' => 12,
                'created_at' => '2018-12-27 02:25:28',
                'updated_at' => '2018-12-27 02:25:28',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            9 => 
            array (
                'id' => 10,
                'unit_type_id' => 13,
                'category_project_id' => 13,
                'created_at' => '2018-12-27 02:28:08',
                'updated_at' => '2018-12-27 02:28:08',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            10 => 
            array (
                'id' => 11,
                'unit_type_id' => 14,
                'category_project_id' => 14,
                'created_at' => '2018-12-27 02:49:51',
                'updated_at' => '2018-12-27 02:49:51',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            11 => 
            array (
                'id' => 12,
                'unit_type_id' => 17,
                'category_project_id' => 15,
                'created_at' => '2018-12-27 02:54:07',
                'updated_at' => '2018-12-27 02:54:07',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            12 => 
            array (
                'id' => 13,
                'unit_type_id' => 18,
                'category_project_id' => 16,
                'created_at' => '2018-12-27 02:55:14',
                'updated_at' => '2018-12-27 02:55:14',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            13 => 
            array (
                'id' => 14,
                'unit_type_id' => 20,
                'category_project_id' => 17,
                'created_at' => '2018-12-27 03:20:41',
                'updated_at' => '2018-12-27 03:20:41',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            14 => 
            array (
                'id' => 15,
                'unit_type_id' => 21,
                'category_project_id' => 18,
                'created_at' => '2018-12-27 03:28:00',
                'updated_at' => '2018-12-27 03:28:00',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            15 => 
            array (
                'id' => 16,
                'unit_type_id' => 63,
                'category_project_id' => 19,
                'created_at' => '2018-12-28 01:39:04',
                'updated_at' => '2018-12-28 01:39:04',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            16 => 
            array (
                'id' => 17,
                'unit_type_id' => 64,
                'category_project_id' => 20,
                'created_at' => '2018-12-28 01:39:45',
                'updated_at' => '2018-12-28 01:39:45',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            17 => 
            array (
                'id' => 18,
                'unit_type_id' => 65,
                'category_project_id' => 21,
                'created_at' => '2018-12-28 01:40:26',
                'updated_at' => '2018-12-28 01:40:26',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            18 => 
            array (
                'id' => 19,
                'unit_type_id' => 66,
                'category_project_id' => 22,
                'created_at' => '2018-12-28 01:41:06',
                'updated_at' => '2018-12-28 01:41:06',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            19 => 
            array (
                'id' => 20,
                'unit_type_id' => 67,
                'category_project_id' => 23,
                'created_at' => '2018-12-28 01:41:56',
                'updated_at' => '2018-12-28 01:41:56',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            20 => 
            array (
                'id' => 21,
                'unit_type_id' => 68,
                'category_project_id' => 24,
                'created_at' => '2018-12-28 01:42:39',
                'updated_at' => '2018-12-28 01:42:39',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            21 => 
            array (
                'id' => 22,
                'unit_type_id' => 69,
                'category_project_id' => 25,
                'created_at' => '2018-12-28 01:43:32',
                'updated_at' => '2018-12-28 01:43:32',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            22 => 
            array (
                'id' => 23,
                'unit_type_id' => 70,
                'category_project_id' => 26,
                'created_at' => '2018-12-28 01:44:12',
                'updated_at' => '2018-12-28 01:44:12',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            23 => 
            array (
                'id' => 24,
                'unit_type_id' => 71,
                'category_project_id' => 27,
                'created_at' => '2018-12-28 01:45:35',
                'updated_at' => '2018-12-28 01:45:35',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            24 => 
            array (
                'id' => 25,
                'unit_type_id' => 72,
                'category_project_id' => 28,
                'created_at' => '2018-12-28 01:51:19',
                'updated_at' => '2018-12-28 01:51:19',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            25 => 
            array (
                'id' => 26,
                'unit_type_id' => 74,
                'category_project_id' => 29,
                'created_at' => '2018-12-28 02:40:58',
                'updated_at' => '2018-12-28 02:40:58',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            26 => 
            array (
                'id' => 27,
                'unit_type_id' => 75,
                'category_project_id' => 30,
                'created_at' => '2018-12-28 02:42:04',
                'updated_at' => '2018-12-28 02:42:04',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            27 => 
            array (
                'id' => 28,
                'unit_type_id' => 76,
                'category_project_id' => 31,
                'created_at' => '2018-12-28 02:44:01',
                'updated_at' => '2018-12-28 02:44:01',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            28 => 
            array (
                'id' => 29,
                'unit_type_id' => 259,
                'category_project_id' => 32,
                'created_at' => '2019-01-08 03:37:11',
                'updated_at' => '2019-01-08 03:37:11',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            29 => 
            array (
                'id' => 30,
                'unit_type_id' => 260,
                'category_project_id' => 33,
                'created_at' => '2019-01-09 02:15:27',
                'updated_at' => '2019-01-09 02:15:27',
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '5',
            ),
            30 => 
            array (
                'id' => 31,
                'unit_type_id' => 261,
                'category_project_id' => 34,
                'created_at' => '2019-01-09 06:58:45',
                'updated_at' => '2019-01-09 06:58:45',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            31 => 
            array (
                'id' => 32,
                'unit_type_id' => 262,
                'category_project_id' => 35,
                'created_at' => '2019-01-09 07:04:28',
                'updated_at' => '2019-01-09 07:04:28',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            32 => 
            array (
                'id' => 33,
                'unit_type_id' => 263,
                'category_project_id' => 36,
                'created_at' => '2019-01-09 07:07:38',
                'updated_at' => '2019-01-09 07:07:38',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            33 => 
            array (
                'id' => 34,
                'unit_type_id' => 264,
                'category_project_id' => 37,
                'created_at' => '2019-01-09 07:10:02',
                'updated_at' => '2019-01-09 07:10:02',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            34 => 
            array (
                'id' => 35,
                'unit_type_id' => 265,
                'category_project_id' => 38,
                'created_at' => '2019-01-09 07:13:02',
                'updated_at' => '2019-01-09 07:13:02',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            35 => 
            array (
                'id' => 36,
                'unit_type_id' => 266,
                'category_project_id' => 39,
                'created_at' => '2019-01-09 07:18:42',
                'updated_at' => '2019-01-09 07:18:42',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            36 => 
            array (
                'id' => 37,
                'unit_type_id' => 267,
                'category_project_id' => 40,
                'created_at' => '2019-01-09 07:21:58',
                'updated_at' => '2019-01-09 07:21:58',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            37 => 
            array (
                'id' => 38,
                'unit_type_id' => 268,
                'category_project_id' => 41,
                'created_at' => '2019-01-09 07:24:49',
                'updated_at' => '2019-01-09 07:24:49',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            38 => 
            array (
                'id' => 39,
                'unit_type_id' => 269,
                'category_project_id' => 42,
                'created_at' => '2019-01-09 07:27:13',
                'updated_at' => '2019-01-09 07:27:13',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            39 => 
            array (
                'id' => 40,
                'unit_type_id' => 270,
                'category_project_id' => 43,
                'created_at' => '2019-01-09 07:31:48',
                'updated_at' => '2019-01-09 07:31:48',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            40 => 
            array (
                'id' => 41,
                'unit_type_id' => 271,
                'category_project_id' => 44,
                'created_at' => '2019-01-09 07:33:58',
                'updated_at' => '2019-01-09 07:33:58',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            41 => 
            array (
                'id' => 42,
                'unit_type_id' => 272,
                'category_project_id' => 45,
                'created_at' => '2019-01-09 07:36:29',
                'updated_at' => '2019-01-09 07:36:29',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            42 => 
            array (
                'id' => 43,
                'unit_type_id' => 273,
                'category_project_id' => 46,
                'created_at' => '2019-01-09 07:40:10',
                'updated_at' => '2019-01-09 07:40:10',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            43 => 
            array (
                'id' => 44,
                'unit_type_id' => 274,
                'category_project_id' => 47,
                'created_at' => '2019-01-09 07:43:12',
                'updated_at' => '2019-01-09 07:43:12',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            44 => 
            array (
                'id' => 45,
                'unit_type_id' => 275,
                'category_project_id' => 48,
                'created_at' => '2019-01-09 07:44:52',
                'updated_at' => '2019-01-09 07:44:52',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            45 => 
            array (
                'id' => 46,
                'unit_type_id' => 276,
                'category_project_id' => 49,
                'created_at' => '2019-01-09 07:48:56',
                'updated_at' => '2019-01-09 07:48:56',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            46 => 
            array (
                'id' => 47,
                'unit_type_id' => 277,
                'category_project_id' => 50,
                'created_at' => '2019-01-09 07:53:28',
                'updated_at' => '2019-01-09 07:53:28',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            47 => 
            array (
                'id' => 48,
                'unit_type_id' => 278,
                'category_project_id' => 51,
                'created_at' => '2019-01-09 07:57:09',
                'updated_at' => '2019-01-09 07:57:09',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            48 => 
            array (
                'id' => 49,
                'unit_type_id' => 279,
                'category_project_id' => 52,
                'created_at' => '2019-01-09 08:02:53',
                'updated_at' => '2019-01-09 08:02:53',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            49 => 
            array (
                'id' => 50,
                'unit_type_id' => 280,
                'category_project_id' => 53,
                'created_at' => '2019-01-09 08:05:35',
                'updated_at' => '2019-01-09 08:05:35',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            50 => 
            array (
                'id' => 51,
                'unit_type_id' => 281,
                'category_project_id' => 54,
                'created_at' => '2019-01-09 08:07:58',
                'updated_at' => '2019-01-09 08:07:58',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            51 => 
            array (
                'id' => 52,
                'unit_type_id' => 282,
                'category_project_id' => 55,
                'created_at' => '2019-01-09 08:10:54',
                'updated_at' => '2019-01-09 08:10:54',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            52 => 
            array (
                'id' => 53,
                'unit_type_id' => 283,
                'category_project_id' => 56,
                'created_at' => '2019-01-09 08:14:40',
                'updated_at' => '2019-01-09 08:14:40',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            53 => 
            array (
                'id' => 54,
                'unit_type_id' => 284,
                'category_project_id' => 57,
                'created_at' => '2019-01-09 08:26:21',
                'updated_at' => '2019-01-09 08:26:21',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            54 => 
            array (
                'id' => 55,
                'unit_type_id' => 285,
                'category_project_id' => 58,
                'created_at' => '2019-01-09 08:30:03',
                'updated_at' => '2019-01-09 08:30:03',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            55 => 
            array (
                'id' => 56,
                'unit_type_id' => 286,
                'category_project_id' => 59,
                'created_at' => '2019-01-09 08:35:34',
                'updated_at' => '2019-01-09 08:35:34',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            56 => 
            array (
                'id' => 57,
                'unit_type_id' => 287,
                'category_project_id' => 60,
                'created_at' => '2019-01-09 08:39:10',
                'updated_at' => '2019-01-09 08:39:10',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            57 => 
            array (
                'id' => 58,
                'unit_type_id' => 288,
                'category_project_id' => 61,
                'created_at' => '2019-01-09 08:42:33',
                'updated_at' => '2019-01-09 08:42:33',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            58 => 
            array (
                'id' => 59,
                'unit_type_id' => 289,
                'category_project_id' => 62,
                'created_at' => '2019-01-09 08:45:36',
                'updated_at' => '2019-01-09 08:45:36',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            59 => 
            array (
                'id' => 60,
                'unit_type_id' => 292,
                'category_project_id' => 63,
                'created_at' => '2019-01-09 08:56:14',
                'updated_at' => '2019-01-09 08:56:14',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            60 => 
            array (
                'id' => 61,
                'unit_type_id' => 293,
                'category_project_id' => 64,
                'created_at' => '2019-01-09 09:01:11',
                'updated_at' => '2019-01-09 09:01:11',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            61 => 
            array (
                'id' => 62,
                'unit_type_id' => 294,
                'category_project_id' => 65,
                'created_at' => '2019-01-09 09:04:15',
                'updated_at' => '2019-01-09 09:04:15',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            62 => 
            array (
                'id' => 63,
                'unit_type_id' => 295,
                'category_project_id' => 66,
                'created_at' => '2019-01-09 09:09:33',
                'updated_at' => '2019-01-09 09:09:33',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            63 => 
            array (
                'id' => 64,
                'unit_type_id' => 297,
                'category_project_id' => 67,
                'created_at' => '2019-01-09 09:11:19',
                'updated_at' => '2019-01-09 09:11:19',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            64 => 
            array (
                'id' => 65,
                'unit_type_id' => 299,
                'category_project_id' => 68,
                'created_at' => '2019-01-09 09:16:50',
                'updated_at' => '2019-01-09 09:16:50',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            65 => 
            array (
                'id' => 66,
                'unit_type_id' => 300,
                'category_project_id' => 69,
                'created_at' => '2019-01-09 09:20:34',
                'updated_at' => '2019-01-09 09:20:34',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            66 => 
            array (
                'id' => 67,
                'unit_type_id' => 302,
                'category_project_id' => 70,
                'created_at' => '2019-01-09 09:26:13',
                'updated_at' => '2019-01-09 09:26:13',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            67 => 
            array (
                'id' => 68,
                'unit_type_id' => 303,
                'category_project_id' => 71,
                'created_at' => '2019-01-09 09:27:52',
                'updated_at' => '2019-01-09 09:27:52',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
            68 => 
            array (
                'id' => 69,
                'unit_type_id' => 304,
                'category_project_id' => 72,
                'created_at' => '2019-01-09 09:29:33',
                'updated_at' => '2019-01-09 09:29:33',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            69 => 
            array (
                'id' => 70,
                'unit_type_id' => 305,
                'category_project_id' => 73,
                'created_at' => '2019-01-09 09:30:55',
                'updated_at' => '2019-01-09 09:30:55',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            70 => 
            array (
                'id' => 71,
                'unit_type_id' => 306,
                'category_project_id' => 74,
                'created_at' => '2019-01-09 09:32:18',
                'updated_at' => '2019-01-09 09:32:18',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            71 => 
            array (
                'id' => 72,
                'unit_type_id' => 307,
                'category_project_id' => 75,
                'created_at' => '2019-01-09 09:33:22',
                'updated_at' => '2019-01-09 09:33:22',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            72 => 
            array (
                'id' => 73,
                'unit_type_id' => 308,
                'category_project_id' => 76,
                'created_at' => '2019-01-09 09:34:37',
                'updated_at' => '2019-01-09 09:34:37',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '4',
            ),
            73 => 
            array (
                'id' => 74,
                'unit_type_id' => 309,
                'category_project_id' => 77,
                'created_at' => '2019-01-09 09:41:08',
                'updated_at' => '2019-01-09 09:41:08',
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '1',
            ),
            74 => 
            array (
                'id' => 75,
                'unit_type_id' => 310,
                'category_project_id' => 78,
                'created_at' => '2019-01-09 10:19:25',
                'updated_at' => '2019-01-09 10:19:25',
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '3',
            ),
            75 => 
            array (
                'id' => 76,
                'unit_type_id' => 313,
                'category_project_id' => 79,
                'created_at' => '2019-01-18 11:14:54',
                'updated_at' => '2019-01-18 11:14:54',
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'type' => '2',
            ),
        ));
        
        
    }
}