<?php

use Illuminate\Database\Seeder;

class BloksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bloks')->delete();
        
        \DB::table('bloks')->insert(array (
            0 => 
            array (
                'id' => 25,
                'project_id' => 66,
                'project_kawasan_id' => 12,
                'name' => 'Blok A',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 22:57:05',
                'updated_at' => '2018-10-25 22:57:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A',
                'block_id' => 3356,
            ),
            1 => 
            array (
                'id' => 26,
                'project_id' => 66,
                'project_kawasan_id' => 12,
                'name' => 'Blok B',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 22:57:05',
                'updated_at' => '2018-10-25 22:57:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'B',
                'block_id' => 3357,
            ),
            2 => 
            array (
                'id' => 27,
                'project_id' => 66,
                'project_kawasan_id' => 12,
                'name' => 'Blok C',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 22:57:05',
                'updated_at' => '2018-10-25 22:57:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'C',
                'block_id' => 3358,
            ),
            3 => 
            array (
                'id' => 28,
                'project_id' => 66,
                'project_kawasan_id' => 12,
                'name' => 'Blok D',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-10-25 22:57:05',
                'updated_at' => '2018-10-25 22:57:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'D',
                'block_id' => 3359,
            ),
            4 => 
            array (
                'id' => 29,
                'project_id' => 66,
                'project_kawasan_id' => 12,
                'name' => 'Blok E',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-26 00:42:05',
                'updated_at' => '2018-10-26 00:42:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'E',
                'block_id' => 3340,
            ),
            5 => 
            array (
                'id' => 31,
                'project_id' => 82,
                'project_kawasan_id' => 13,
                'name' => 'A1',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-31 20:36:29',
                'updated_at' => '2018-10-31 20:36:29',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A',
                'block_id' => NULL,
            ),
            6 => 
            array (
                'id' => 32,
                'project_id' => 82,
                'project_kawasan_id' => 13,
                'name' => 'A2',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-31 21:07:36',
                'updated_at' => '2018-10-31 21:07:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A2',
                'block_id' => NULL,
            ),
            7 => 
            array (
                'id' => 33,
                'project_id' => 82,
                'project_kawasan_id' => 13,
                'name' => 'A3',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-31 21:14:11',
                'updated_at' => '2018-10-31 21:14:11',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A3',
                'block_id' => NULL,
            ),
            8 => 
            array (
                'id' => 34,
                'project_id' => 82,
                'project_kawasan_id' => 14,
                'name' => 'A4',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-31 21:14:59',
                'updated_at' => '2018-10-31 21:14:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A4',
                'block_id' => NULL,
            ),
            9 => 
            array (
                'id' => 35,
                'project_id' => 82,
                'project_kawasan_id' => 14,
                'name' => 'A5',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-31 21:16:08',
                'updated_at' => '2018-10-31 21:16:08',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A5',
                'block_id' => NULL,
            ),
            10 => 
            array (
                'id' => 37,
                'project_id' => 9,
                'project_kawasan_id' => 35,
                'name' => 'C09',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-13 12:38:26',
                'updated_at' => '2018-11-13 13:14:11',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'C09',
                'block_id' => 15300,
            ),
            11 => 
            array (
                'id' => 38,
                'project_id' => 9,
                'project_kawasan_id' => 35,
                'name' => 'C10',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-13 12:43:02',
                'updated_at' => '2018-11-13 13:22:08',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'C10',
                'block_id' => 15301,
            ),
            12 => 
            array (
                'id' => 39,
                'project_id' => 9,
                'project_kawasan_id' => 35,
                'name' => 'C11',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-13 12:47:31',
                'updated_at' => '2018-11-13 12:47:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'C11',
                'block_id' => 15302,
            ),
            13 => 
            array (
                'id' => 40,
                'project_id' => 9,
                'project_kawasan_id' => 39,
                'name' => 'D01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-13 12:54:39',
                'updated_at' => '2018-11-13 13:21:13',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'D01',
                'block_id' => 15303,
            ),
            14 => 
            array (
                'id' => 41,
                'project_id' => 9,
                'project_kawasan_id' => 39,
                'name' => 'D02',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-13 13:19:25',
                'updated_at' => '2018-11-13 13:19:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'D02',
                'block_id' => 15304,
            ),
            15 => 
            array (
                'id' => 42,
                'project_id' => 9,
                'project_kawasan_id' => 41,
                'name' => 'A1',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-15 10:09:53',
                'updated_at' => '2018-11-15 10:10:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A1',
                'block_id' => 15307,
            ),
            16 => 
            array (
                'id' => 43,
                'project_id' => 9,
                'project_kawasan_id' => 41,
                'name' => 'A2',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-15 10:10:48',
                'updated_at' => '2018-11-15 10:10:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A2',
                'block_id' => 15308,
            ),
            17 => 
            array (
                'id' => 44,
                'project_id' => 9,
                'project_kawasan_id' => 40,
                'name' => 'A3',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-15 10:15:19',
                'updated_at' => '2018-11-15 10:15:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A3',
                'block_id' => 15309,
            ),
            18 => 
            array (
                'id' => 45,
                'project_id' => 9,
                'project_kawasan_id' => 40,
                'name' => 'A4',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-15 10:15:48',
                'updated_at' => '2018-11-15 10:15:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A4',
                'block_id' => 15310,
            ),
            19 => 
            array (
                'id' => 46,
                'project_id' => 9,
                'project_kawasan_id' => 41,
                'name' => 'A5',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-11-15 10:16:21',
                'updated_at' => '2018-11-15 10:16:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A5',
                'block_id' => 15311,
            ),
            20 => 
            array (
                'id' => 47,
                'project_id' => 9,
                'project_kawasan_id' => 42,
                'name' => '2',
                'luas' => 2.0,
                'description' => NULL,
                'created_at' => '2018-12-17 08:29:59',
                'updated_at' => '2018-12-17 08:29:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => '2',
                'block_id' => NULL,
            ),
            21 => 
            array (
                'id' => 69,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'BLOK CC',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-20 08:55:14',
                'updated_at' => '2018-12-20 08:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CLGRD',
                'block_id' => 15293,
            ),
            22 => 
            array (
                'id' => 70,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC10',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-26 09:20:37',
                'updated_at' => '2018-12-26 09:20:37',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC10',
                'block_id' => NULL,
            ),
            23 => 
            array (
                'id' => 71,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC11',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-26 09:26:17',
                'updated_at' => '2018-12-26 09:26:17',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC11',
                'block_id' => NULL,
            ),
            24 => 
            array (
                'id' => 72,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC12',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-26 09:32:42',
                'updated_at' => '2018-12-26 09:32:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC12',
                'block_id' => NULL,
            ),
            25 => 
            array (
                'id' => 73,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC15',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-26 09:34:02',
                'updated_at' => '2018-12-26 09:34:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC15',
                'block_id' => NULL,
            ),
            26 => 
            array (
                'id' => 114,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC1',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:30:47',
                'updated_at' => '2018-12-27 07:30:47',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC1',
                'block_id' => NULL,
            ),
            27 => 
            array (
                'id' => 115,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC2',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:30:59',
                'updated_at' => '2018-12-27 07:30:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC2',
                'block_id' => NULL,
            ),
            28 => 
            array (
                'id' => 116,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC03',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:31:15',
                'updated_at' => '2018-12-27 07:31:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC03',
                'block_id' => NULL,
            ),
            29 => 
            array (
                'id' => 117,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC05',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:31:42',
                'updated_at' => '2018-12-27 07:31:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC05',
                'block_id' => NULL,
            ),
            30 => 
            array (
                'id' => 118,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC06',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:31:59',
                'updated_at' => '2018-12-27 07:31:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC06',
                'block_id' => NULL,
            ),
            31 => 
            array (
                'id' => 119,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC07',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:32:11',
                'updated_at' => '2018-12-27 07:32:11',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC07',
                'block_id' => NULL,
            ),
            32 => 
            array (
                'id' => 120,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC08',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:32:25',
                'updated_at' => '2018-12-27 07:32:25',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC08',
                'block_id' => NULL,
            ),
            33 => 
            array (
                'id' => 121,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC09',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:32:53',
                'updated_at' => '2018-12-27 07:32:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC09',
                'block_id' => NULL,
            ),
            34 => 
            array (
                'id' => 122,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC17',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 07:48:19',
                'updated_at' => '2018-12-27 07:48:19',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC17',
                'block_id' => NULL,
            ),
            35 => 
            array (
                'id' => 123,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CC16',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-27 08:26:34',
                'updated_at' => '2018-12-27 08:26:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CC16',
                'block_id' => NULL,
            ),
            36 => 
            array (
                'id' => 124,
                'project_id' => 3,
                'project_kawasan_id' => 65,
                'name' => 'AA05',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-28 03:01:51',
                'updated_at' => '2018-12-28 03:01:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AA05',
                'block_id' => 3406,
            ),
            37 => 
            array (
                'id' => 125,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB01',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB01',
                'block_id' => 3424,
            ),
            38 => 
            array (
                'id' => 126,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB02',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB02',
                'block_id' => 3425,
            ),
            39 => 
            array (
                'id' => 127,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB03',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB03',
                'block_id' => 3426,
            ),
            40 => 
            array (
                'id' => 128,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB05',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB05',
                'block_id' => 3427,
            ),
            41 => 
            array (
                'id' => 129,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB06',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB06',
                'block_id' => 3428,
            ),
            42 => 
            array (
                'id' => 130,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB07',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB07',
                'block_id' => 3429,
            ),
            43 => 
            array (
                'id' => 131,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB08',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB08',
                'block_id' => 3430,
            ),
            44 => 
            array (
                'id' => 132,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB09',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB09',
                'block_id' => 3431,
            ),
            45 => 
            array (
                'id' => 133,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'name' => 'Blok BB10',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 03:21:44',
                'updated_at' => '2018-12-28 03:21:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BB10',
                'block_id' => 3432,
            ),
            46 => 
            array (
                'id' => 134,
                'project_id' => 3,
                'project_kawasan_id' => 67,
                'name' => 'Blok Q01',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 05:15:51',
                'updated_at' => '2018-12-28 05:15:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'Q01',
                'block_id' => 3615,
            ),
            47 => 
            array (
                'id' => 135,
                'project_id' => 3,
                'project_kawasan_id' => 67,
                'name' => 'Blok Q02',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 05:15:51',
                'updated_at' => '2018-12-28 05:15:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'Q02',
                'block_id' => 3616,
            ),
            48 => 
            array (
                'id' => 136,
                'project_id' => 3,
                'project_kawasan_id' => 67,
                'name' => 'Blok Q03',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 05:15:51',
                'updated_at' => '2018-12-28 05:15:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'Q03',
                'block_id' => 3617,
            ),
            49 => 
            array (
                'id' => 137,
                'project_id' => 3,
                'project_kawasan_id' => 67,
                'name' => 'Blok Q05',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 05:15:51',
                'updated_at' => '2018-12-28 05:15:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'Q05',
                'block_id' => 3618,
            ),
            50 => 
            array (
                'id' => 138,
                'project_id' => 3,
                'project_kawasan_id' => 67,
                'name' => 'Blok Q06',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 05:15:51',
                'updated_at' => '2018-12-28 05:15:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'Q06',
                'block_id' => 3619,
            ),
            51 => 
            array (
                'id' => 139,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.17',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.17',
                'block_id' => 2342,
            ),
            52 => 
            array (
                'id' => 140,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.11',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.11',
                'block_id' => 2354,
            ),
            53 => 
            array (
                'id' => 141,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.02',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.02',
                'block_id' => 2372,
            ),
            54 => 
            array (
                'id' => 142,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.16',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.16',
                'block_id' => 2391,
            ),
            55 => 
            array (
                'id' => 143,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.12',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.12',
                'block_id' => 2842,
            ),
            56 => 
            array (
                'id' => 144,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.05',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.05',
                'block_id' => 2867,
            ),
            57 => 
            array (
                'id' => 145,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.03',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.03',
                'block_id' => 2949,
            ),
            58 => 
            array (
                'id' => 146,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'BLOK BE.06',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.06',
                'block_id' => 3350,
            ),
            59 => 
            array (
                'id' => 147,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE.15',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.15',
                'block_id' => 3396,
            ),
            60 => 
            array (
                'id' => 148,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'BLOK BE.08',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.08',
                'block_id' => 4941,
            ),
            61 => 
            array (
                'id' => 149,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'BLOK BE.09',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.09',
                'block_id' => 6307,
            ),
            62 => 
            array (
                'id' => 150,
                'project_id' => 1,
                'project_kawasan_id' => 48,
                'name' => 'BLOK BE.0A',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.0A',
                'block_id' => 9750,
            ),
            63 => 
            array (
                'id' => 151,
                'project_id' => 1,
                'project_kawasan_id' => 48,
                'name' => 'BLOK BE.0B',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BLOK ',
                'block_id' => 9752,
            ),
            64 => 
            array (
                'id' => 152,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.01',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.01',
                'block_id' => 14067,
            ),
            65 => 
            array (
                'id' => 153,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.10',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.10',
                'block_id' => 14068,
            ),
            66 => 
            array (
                'id' => 154,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.09',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.09',
                'block_id' => 14075,
            ),
            67 => 
            array (
                'id' => 155,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.16',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.16',
                'block_id' => 14076,
            ),
            68 => 
            array (
                'id' => 156,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.17',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.17',
                'block_id' => 14079,
            ),
            69 => 
            array (
                'id' => 157,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.15',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.15',
                'block_id' => 14080,
            ),
            70 => 
            array (
                'id' => 158,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.12',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.12',
                'block_id' => 14081,
            ),
            71 => 
            array (
                'id' => 159,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.11',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.11',
                'block_id' => 14082,
            ),
            72 => 
            array (
                'id' => 160,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.08',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.08',
                'block_id' => 14083,
            ),
            73 => 
            array (
                'id' => 161,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.07',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.07',
                'block_id' => 14084,
            ),
            74 => 
            array (
                'id' => 162,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.05',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.05',
                'block_id' => 14085,
            ),
            75 => 
            array (
                'id' => 163,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.03',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.03',
                'block_id' => 14086,
            ),
            76 => 
            array (
                'id' => 164,
                'project_id' => 1,
                'project_kawasan_id' => 45,
                'name' => 'BLOK AZ.02',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.02',
                'block_id' => 14087,
            ),
            77 => 
            array (
                'id' => 165,
                'project_id' => 1,
                'project_kawasan_id' => NULL,
                'name' => 'BLOK AZ.06',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AZ.06',
                'block_id' => 14088,
            ),
            78 => 
            array (
                'id' => 166,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'BLOK BE.07',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.07',
                'block_id' => 15251,
            ),
            79 => 
            array (
                'id' => 167,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'BLOK BE.10',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE.10',
                'block_id' => 15281,
            ),
            80 => 
            array (
                'id' => 168,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.01',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.01',
                'block_id' => 15282,
            ),
            81 => 
            array (
                'id' => 169,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.09',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.09',
                'block_id' => 15283,
            ),
            82 => 
            array (
                'id' => 170,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.10',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.10',
                'block_id' => 15284,
            ),
            83 => 
            array (
                'id' => 171,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.16',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.16',
                'block_id' => 15289,
            ),
            84 => 
            array (
                'id' => 172,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.15',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.15',
                'block_id' => 15290,
            ),
            85 => 
            array (
                'id' => 173,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.12',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.12',
                'block_id' => 15291,
            ),
            86 => 
            array (
                'id' => 174,
                'project_id' => 1,
                'project_kawasan_id' => NULL,
                'name' => 'BLOK BG.11',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.11',
                'block_id' => 15292,
            ),
            87 => 
            array (
                'id' => 175,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.08',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.08',
                'block_id' => 15411,
            ),
            88 => 
            array (
                'id' => 176,
                'project_id' => 1,
                'project_kawasan_id' => 46,
                'name' => 'BLOK BG.06',
                'luas' => 0.0,
                'description' => 'Migration from Erem based export at 18 Des 2018',
                'created_at' => '2018-12-28 07:26:59',
                'updated_at' => '2018-12-28 07:26:59',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BG.06',
                'block_id' => 16437,
            ),
            89 => 
            array (
                'id' => 177,
                'project_id' => 1,
                'project_kawasan_id' => 47,
                'name' => 'Blok BE01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-28 08:10:01',
                'updated_at' => '2018-12-28 08:10:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'BE01',
                'block_id' => NULL,
            ),
            90 => 
            array (
                'id' => 178,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'name' => 'CCKVL',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-12-28 08:52:22',
                'updated_at' => '2018-12-28 08:52:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'CCKVL',
                'block_id' => NULL,
            ),
            91 => 
            array (
                'id' => 180,
                'project_id' => 9,
                'project_kawasan_id' => 68,
                'name' => 'Blok A',
                'luas' => 2000.0,
                'description' => NULL,
                'created_at' => '2018-12-31 09:17:14',
                'updated_at' => '2018-12-31 09:32:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A',
                'block_id' => NULL,
            ),
            92 => 
            array (
                'id' => 181,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'AR01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:42:07',
                'updated_at' => '2018-10-01 22:42:07',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AR',
                'block_id' => 15267,
            ),
            93 => 
            array (
                'id' => 182,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'name' => 'E01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:42:53',
                'updated_at' => '2018-10-01 22:42:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'E01',
                'block_id' => 9757,
            ),
            94 => 
            array (
                'id' => 183,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'name' => 'E02',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:43:04',
                'updated_at' => '2018-10-01 22:43:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'E02',
                'block_id' => 9759,
            ),
            95 => 
            array (
                'id' => 184,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'name' => 'E03',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:43:12',
                'updated_at' => '2018-10-01 22:43:12',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'E03',
                'block_id' => 9760,
            ),
            96 => 
            array (
                'id' => 185,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'name' => 'E05',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:43:23',
                'updated_at' => '2018-10-01 22:43:23',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'E05',
                'block_id' => 9761,
            ),
            97 => 
            array (
                'id' => 186,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'name' => 'E06',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:43:30',
                'updated_at' => '2018-10-01 22:43:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'E06',
                'block_id' => 9762,
            ),
            98 => 
            array (
                'id' => 187,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'ER01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:43:47',
                'updated_at' => '2018-10-01 22:43:47',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'ER01',
                'block_id' => 9763,
            ),
            99 => 
            array (
                'id' => 188,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'ER02',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:44:06',
                'updated_at' => '2018-10-01 22:44:06',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'ER02',
                'block_id' => 10797,
            ),
            100 => 
            array (
                'id' => 189,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:45:21',
                'updated_at' => '2018-10-01 22:45:21',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F01',
                'block_id' => 9744,
            ),
            101 => 
            array (
                'id' => 190,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F02',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:45:42',
                'updated_at' => '2018-10-01 22:45:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F02',
                'block_id' => 9747,
            ),
            102 => 
            array (
                'id' => 191,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F03',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:46:57',
                'updated_at' => '2018-10-01 22:46:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F03',
                'block_id' => 9748,
            ),
            103 => 
            array (
                'id' => 192,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F05',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:47:15',
                'updated_at' => '2018-10-01 22:47:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F05',
                'block_id' => 9749,
            ),
            104 => 
            array (
                'id' => 193,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F06',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:47:31',
                'updated_at' => '2018-10-01 22:47:31',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F06',
                'block_id' => 9751,
            ),
            105 => 
            array (
                'id' => 194,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F07',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:47:40',
                'updated_at' => '2018-10-01 22:47:40',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F07',
                'block_id' => 9753,
            ),
            106 => 
            array (
                'id' => 195,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F08',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:47:52',
                'updated_at' => '2018-10-01 22:47:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F08',
                'block_id' => 9754,
            ),
            107 => 
            array (
                'id' => 196,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F09',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:48:09',
                'updated_at' => '2018-10-01 22:48:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F09',
                'block_id' => 15265,
            ),
            108 => 
            array (
                'id' => 197,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'name' => 'F10',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:48:17',
                'updated_at' => '2018-10-01 22:48:17',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'F10',
                'block_id' => 15256,
            ),
            109 => 
            array (
                'id' => 198,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'FR01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:48:33',
                'updated_at' => '2018-10-01 22:48:33',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'FR01',
                'block_id' => 9766,
            ),
            110 => 
            array (
                'id' => 199,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'FR02',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:49:15',
                'updated_at' => '2018-10-01 22:49:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'FR02',
                'block_id' => 10799,
            ),
            111 => 
            array (
                'id' => 200,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'FR03',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:50:02',
                'updated_at' => '2018-10-01 22:50:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'FR03',
                'block_id' => 15264,
            ),
            112 => 
            array (
                'id' => 201,
                'project_id' => 60,
                'project_kawasan_id' => 72,
                'name' => 'KVC',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:52:15',
                'updated_at' => '2018-10-01 22:52:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'KVC',
                'block_id' => NULL,
            ),
            113 => 
            array (
                'id' => 202,
                'project_id' => 60,
                'project_kawasan_id' => 73,
                'name' => 'KVD',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:54:24',
                'updated_at' => '2018-10-01 22:54:24',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'KVD',
                'block_id' => NULL,
            ),
            114 => 
            array (
                'id' => 204,
                'project_id' => 60,
                'project_kawasan_id' => 72,
                'name' => 'KVH',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:55:06',
                'updated_at' => '2018-10-01 22:55:06',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'KVG',
                'block_id' => NULL,
            ),
            115 => 
            array (
                'id' => 205,
                'project_id' => 60,
                'project_kawasan_id' => 73,
                'name' => 'KVI',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 22:55:12',
                'updated_at' => '2018-10-01 22:55:12',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'KVI',
                'block_id' => NULL,
            ),
            116 => 
            array (
                'id' => 207,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'GR03',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2018-10-01 23:10:04',
                'updated_at' => '2019-01-14 07:51:49',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'ER03',
                'block_id' => NULL,
            ),
            117 => 
            array (
                'id' => 217,
                'project_id' => 3,
                'project_kawasan_id' => 80,
                'name' => 'I KT',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 02:10:55',
                'updated_at' => '2019-01-09 02:10:55',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'RIKT',
                'block_id' => NULL,
            ),
            118 => 
            array (
                'id' => 218,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P23',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:56:53',
                'updated_at' => '2019-01-09 04:56:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P23',
                'block_id' => NULL,
            ),
            119 => 
            array (
                'id' => 219,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P25',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:57:10',
                'updated_at' => '2019-01-09 04:57:10',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P25',
                'block_id' => NULL,
            ),
            120 => 
            array (
                'id' => 220,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P26',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:57:20',
                'updated_at' => '2019-01-09 04:57:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P26',
                'block_id' => NULL,
            ),
            121 => 
            array (
                'id' => 221,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P27',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:57:39',
                'updated_at' => '2019-01-09 04:57:39',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P27',
                'block_id' => NULL,
            ),
            122 => 
            array (
                'id' => 222,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P28',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:57:48',
                'updated_at' => '2019-01-09 04:57:48',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P28',
                'block_id' => NULL,
            ),
            123 => 
            array (
                'id' => 223,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P29',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:57:58',
                'updated_at' => '2019-01-09 04:57:58',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P29',
                'block_id' => NULL,
            ),
            124 => 
            array (
                'id' => 224,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P30',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:58:07',
                'updated_at' => '2019-01-09 04:58:07',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P30',
                'block_id' => NULL,
            ),
            125 => 
            array (
                'id' => 225,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'name' => 'P32',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-09 04:58:20',
                'updated_at' => '2019-01-09 04:58:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'P32',
                'block_id' => NULL,
            ),
            126 => 
            array (
                'id' => 226,
                'project_id' => 60,
                'project_kawasan_id' => 70,
                'name' => 'A',
                'luas' => 16915.0,
                'description' => NULL,
                'created_at' => '2019-01-09 10:17:46',
                'updated_at' => '2019-01-09 10:17:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'A',
                'block_id' => NULL,
            ),
            127 => 
            array (
                'id' => 227,
                'project_id' => 60,
                'project_kawasan_id' => 71,
                'name' => 'B',
                'luas' => 23764.0,
                'description' => NULL,
                'created_at' => '2019-01-09 10:39:05',
                'updated_at' => '2019-01-09 10:39:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'B',
                'block_id' => NULL,
            ),
            128 => 
            array (
                'id' => 228,
                'project_id' => 60,
                'project_kawasan_id' => 70,
                'name' => 'AEXT',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-14 06:26:27',
                'updated_at' => '2019-01-14 06:26:27',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'AEXT',
                'block_id' => NULL,
            ),
            129 => 
            array (
                'id' => 229,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'name' => 'EB01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-14 07:16:13',
                'updated_at' => '2019-01-14 07:16:13',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'EB01',
                'block_id' => NULL,
            ),
            130 => 
            array (
                'id' => 230,
                'project_id' => 60,
                'project_kawasan_id' => 76,
                'name' => 'G01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-14 07:23:45',
                'updated_at' => '2019-01-14 07:23:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'G01',
                'block_id' => NULL,
            ),
            131 => 
            array (
                'id' => 231,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'H01',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-14 07:25:28',
                'updated_at' => '2019-01-14 07:25:28',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'H01',
                'block_id' => NULL,
            ),
            132 => 
            array (
                'id' => 232,
                'project_id' => 60,
                'project_kawasan_id' => 78,
                'name' => 'I02',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-14 07:27:08',
                'updated_at' => '2019-01-14 07:27:08',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'I01',
                'block_id' => NULL,
            ),
            133 => 
            array (
                'id' => 233,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'name' => 'IR',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-14 07:39:36',
                'updated_at' => '2019-01-14 07:39:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => 'IR',
                'block_id' => NULL,
            ),
            134 => 
            array (
                'id' => 234,
                'project_id' => 3,
                'project_kawasan_id' => 81,
                'name' => 'blok campur',
                'luas' => 0.0,
                'description' => NULL,
                'created_at' => '2019-01-18 03:19:53',
                'updated_at' => '2019-01-18 03:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'kode' => '11',
                'block_id' => NULL,
            ),
        ));
        
        
    }
}