<?php

use Illuminate\Database\Seeder;

class BudgetTahunanUnitPeriodesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('budget_tahunan_unit_periodes')->delete();
        
        \DB::table('budget_tahunan_unit_periodes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'budget_tahunan_unit_id' => 1,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 1.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 1.0,
                'september' => 1.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 1.0,
            ),
            1 => 
            array (
                'id' => 2,
                'budget_tahunan_unit_id' => 2,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 15.0,
                'april' => 1.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 1.0,
                'agustus' => 1.0,
                'september' => 0.0,
                'oktober' => 1.0,
                'november' => 0.0,
                'desember' => 1.0,
            ),
            2 => 
            array (
                'id' => 3,
                'budget_tahunan_unit_id' => 3,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 7.0,
                'april' => 1.0,
                'mei' => 2.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 1.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 2.0,
                'desember' => 2.0,
            ),
            3 => 
            array (
                'id' => 4,
                'budget_tahunan_unit_id' => 4,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 2.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 2.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 2.0,
                'desember' => 1.0,
            ),
            4 => 
            array (
                'id' => 5,
                'budget_tahunan_unit_id' => 5,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            5 => 
            array (
                'id' => 6,
                'budget_tahunan_unit_id' => 6,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            6 => 
            array (
                'id' => 7,
                'budget_tahunan_unit_id' => 7,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-27 06:22:16',
                'updated_at' => '2018-12-27 06:22:16',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 1.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 1.0,
                'desember' => 0.0,
            ),
            7 => 
            array (
                'id' => 8,
                'budget_tahunan_unit_id' => 8,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-27 06:22:16',
                'updated_at' => '2018-12-27 06:22:16',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 1.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 1.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 1.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            8 => 
            array (
                'id' => 9,
                'budget_tahunan_unit_id' => 9,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-28 04:11:02',
                'updated_at' => '2018-12-28 04:11:02',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 1.0,
                'september' => 1.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            9 => 
            array (
                'id' => 10,
                'budget_tahunan_unit_id' => 10,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-28 04:11:02',
                'updated_at' => '2018-12-28 04:11:02',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 2.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            10 => 
            array (
                'id' => 11,
                'budget_tahunan_unit_id' => 11,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 08:48:05',
                'updated_at' => '2019-01-08 08:48:05',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 1.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            11 => 
            array (
                'id' => 12,
                'budget_tahunan_unit_id' => 12,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 08:48:05',
                'updated_at' => '2019-01-08 08:48:05',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 1.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 1.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 1.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            12 => 
            array (
                'id' => 13,
                'budget_tahunan_unit_id' => 13,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:40:28',
                'updated_at' => '2019-01-08 11:40:28',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 1.0,
                'mei' => 0.0,
                'juni' => 1.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 1.0,
                'desember' => 1.0,
            ),
            13 => 
            array (
                'id' => 14,
                'budget_tahunan_unit_id' => 14,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:49:44',
                'updated_at' => '2019-01-08 11:49:44',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 1.0,
                'mei' => 0.0,
                'juni' => 1.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 1.0,
                'desember' => 1.0,
            ),
            14 => 
            array (
                'id' => 15,
                'budget_tahunan_unit_id' => 15,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:49:44',
                'updated_at' => '2019-01-08 11:49:44',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 1.0,
            ),
            15 => 
            array (
                'id' => 16,
                'budget_tahunan_unit_id' => 16,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:49:44',
                'updated_at' => '2019-01-08 11:49:44',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 1.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            16 => 
            array (
                'id' => 17,
                'budget_tahunan_unit_id' => 17,
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-09 04:42:43',
                'updated_at' => '2019-01-09 04:42:43',
                'januari' => 0.0,
                'februari' => NULL,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 2.0,
                'juni' => 2.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 3.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            17 => 
            array (
                'id' => 18,
                'budget_tahunan_unit_id' => 21,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 21.0,
                'februari' => 4.0,
                'maret' => 2.0,
                'april' => 1.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 1.0,
                'agustus' => 2.0,
                'september' => 1.0,
                'oktober' => 1.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            18 => 
            array (
                'id' => 19,
                'budget_tahunan_unit_id' => 22,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 5.0,
                'februari' => 1.0,
                'maret' => 0.0,
                'april' => 1.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 3.0,
                'agustus' => 2.0,
                'september' => 1.0,
                'oktober' => 2.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            19 => 
            array (
                'id' => 20,
                'budget_tahunan_unit_id' => 23,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 34.0,
                'februari' => 1.0,
                'maret' => 2.0,
                'april' => 2.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 3.0,
                'agustus' => 0.0,
                'september' => 1.0,
                'oktober' => 2.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            20 => 
            array (
                'id' => 21,
                'budget_tahunan_unit_id' => 24,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 3.0,
                'februari' => 0.0,
                'maret' => 1.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            21 => 
            array (
                'id' => 22,
                'budget_tahunan_unit_id' => 25,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 3.0,
                'februari' => 0.0,
                'maret' => 0.0,
                'april' => 0.0,
                'mei' => 0.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 0.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            22 => 
            array (
                'id' => 23,
                'budget_tahunan_unit_id' => 26,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 8.0,
                'februari' => 1.0,
                'maret' => 0.0,
                'april' => 2.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 0.0,
                'agustus' => 0.0,
                'september' => 1.0,
                'oktober' => 0.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
            23 => 
            array (
                'id' => 24,
                'budget_tahunan_unit_id' => 27,
                'deleted_at' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'januari' => 22.0,
                'februari' => 0.0,
                'maret' => 1.0,
                'april' => 1.0,
                'mei' => 1.0,
                'juni' => 0.0,
                'juli' => 1.0,
                'agustus' => 2.0,
                'september' => 1.0,
                'oktober' => 2.0,
                'november' => 0.0,
                'desember' => 0.0,
            ),
        ));
        
        
    }
}