<?php

use Illuminate\Database\Seeder;

class BudgetTahunanUnitPeriodeDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('budget_tahunan_unit_periode_details')->delete();
        
        \DB::table('budget_tahunan_unit_periode_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 1,
                'created_at' => '2018-12-26 10:11:09',
                'updated_at' => '2018-12-26 10:11:09',
            ),
            1 => 
            array (
                'id' => 2,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-26 10:14:01',
                'updated_at' => '2018-12-26 10:14:01',
            ),
            2 => 
            array (
                'id' => 3,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 3,
                'created_at' => '2018-12-26 10:16:40',
                'updated_at' => '2018-12-26 10:16:40',
            ),
            3 => 
            array (
                'id' => 4,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 4,
                'created_at' => '2018-12-26 10:17:32',
                'updated_at' => '2018-12-26 10:17:32',
            ),
            4 => 
            array (
                'id' => 5,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-26 10:18:28',
                'updated_at' => '2018-12-26 10:18:28',
            ),
            5 => 
            array (
                'id' => 6,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 3,
                'created_at' => '2018-12-26 10:19:44',
                'updated_at' => '2018-12-26 10:19:44',
            ),
            6 => 
            array (
                'id' => 7,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-26 10:21:15',
                'updated_at' => '2018-12-26 10:21:15',
            ),
            7 => 
            array (
                'id' => 8,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 3,
                'created_at' => '2018-12-26 10:24:14',
                'updated_at' => '2018-12-26 10:24:14',
            ),
            8 => 
            array (
                'id' => 9,
                'month' => 6,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 4,
                'created_at' => '2018-12-26 10:43:55',
                'updated_at' => '2018-12-26 10:43:55',
            ),
            9 => 
            array (
                'id' => 10,
                'month' => 7,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-26 10:45:06',
                'updated_at' => '2018-12-26 10:45:06',
            ),
            10 => 
            array (
                'id' => 11,
                'month' => 8,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 15,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 1,
                'created_at' => '2018-12-26 10:46:01',
                'updated_at' => '2018-12-26 10:46:01',
            ),
            11 => 
            array (
                'id' => 12,
                'month' => 8,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 15,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-26 10:47:29',
                'updated_at' => '2018-12-26 10:47:29',
            ),
            12 => 
            array (
                'id' => 13,
                'month' => 8,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 15,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 3,
                'created_at' => '2018-12-26 10:48:17',
                'updated_at' => '2018-12-26 10:48:17',
            ),
            13 => 
            array (
                'id' => 14,
                'month' => 9,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 15,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 1,
                'created_at' => '2018-12-27 01:40:24',
                'updated_at' => '2018-12-27 01:40:24',
            ),
            14 => 
            array (
                'id' => 15,
                'month' => 10,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 15,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-27 01:41:04',
                'updated_at' => '2018-12-27 01:41:04',
            ),
            15 => 
            array (
                'id' => 16,
                'month' => 11,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 15,
                'desember' => 10,
                'budget_tahunan_periode' => 3,
                'created_at' => '2018-12-27 01:41:33',
                'updated_at' => '2018-12-27 01:41:33',
            ),
            16 => 
            array (
                'id' => 17,
                'month' => 11,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 15,
                'desember' => 10,
                'budget_tahunan_periode' => 4,
                'created_at' => '2018-12-27 01:42:11',
                'updated_at' => '2018-12-27 01:42:11',
            ),
            17 => 
            array (
                'id' => 18,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 1,
                'created_at' => '2018-12-27 01:42:38',
                'updated_at' => '2018-12-27 01:42:38',
            ),
            18 => 
            array (
                'id' => 19,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-27 01:42:58',
                'updated_at' => '2018-12-27 01:42:58',
            ),
            19 => 
            array (
                'id' => 20,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 2,
                'created_at' => '2018-12-27 01:45:17',
                'updated_at' => '2018-12-27 01:45:17',
            ),
            20 => 
            array (
                'id' => 21,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 3,
                'created_at' => '2018-12-27 01:45:40',
                'updated_at' => '2018-12-27 01:45:40',
            ),
            21 => 
            array (
                'id' => 22,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 4,
                'created_at' => '2018-12-27 01:46:07',
                'updated_at' => '2018-12-27 01:46:07',
            ),
            22 => 
            array (
                'id' => 23,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 7,
                'created_at' => '2018-12-27 06:24:12',
                'updated_at' => '2018-12-27 06:24:12',
            ),
            23 => 
            array (
                'id' => 24,
                'month' => 11,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 15,
                'desember' => 10,
                'budget_tahunan_periode' => 7,
                'created_at' => '2018-12-27 06:24:44',
                'updated_at' => '2018-12-27 06:24:44',
            ),
            24 => 
            array (
                'id' => 25,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 8,
                'created_at' => '2018-12-27 06:25:46',
                'updated_at' => '2018-12-27 06:25:46',
            ),
            25 => 
            array (
                'id' => 26,
                'month' => 7,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 8,
                'created_at' => '2018-12-27 06:26:40',
                'updated_at' => '2018-12-27 06:26:40',
            ),
            26 => 
            array (
                'id' => 27,
                'month' => 10,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 15,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 8,
                'created_at' => '2018-12-27 06:27:10',
                'updated_at' => '2018-12-27 06:27:10',
            ),
            27 => 
            array (
                'id' => 28,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 9,
                'created_at' => '2018-12-28 04:13:39',
                'updated_at' => '2018-12-28 04:13:39',
            ),
            28 => 
            array (
                'id' => 29,
                'month' => 8,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 15,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 9,
                'created_at' => '2018-12-28 04:15:18',
                'updated_at' => '2018-12-28 04:15:18',
            ),
            29 => 
            array (
                'id' => 30,
                'month' => 9,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 15,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 9,
                'created_at' => '2018-12-28 04:16:31',
                'updated_at' => '2018-12-28 04:16:31',
            ),
            30 => 
            array (
                'id' => 31,
                'month' => 7,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 10,
                'created_at' => '2018-12-28 04:17:48',
                'updated_at' => '2018-12-28 04:17:48',
            ),
            31 => 
            array (
                'id' => 32,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 11111,
                'created_at' => '2019-01-08 08:50:25',
                'updated_at' => '2019-01-08 08:50:25',
            ),
            32 => 
            array (
                'id' => 33,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 11111,
                'created_at' => '2019-01-08 08:52:34',
                'updated_at' => '2019-01-08 08:52:34',
            ),
            33 => 
            array (
                'id' => 34,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 11,
                'created_at' => '2019-01-08 08:53:32',
                'updated_at' => '2019-01-08 08:53:32',
            ),
            34 => 
            array (
                'id' => 35,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 1222,
                'created_at' => '2019-01-08 08:54:33',
                'updated_at' => '2019-01-08 08:54:33',
            ),
            35 => 
            array (
                'id' => 36,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 1222,
                'created_at' => '2019-01-08 08:54:58',
                'updated_at' => '2019-01-08 08:54:58',
            ),
            36 => 
            array (
                'id' => 37,
                'month' => 7,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 12,
                'created_at' => '2019-01-08 08:56:00',
                'updated_at' => '2019-01-08 08:56:00',
            ),
            37 => 
            array (
                'id' => 38,
                'month' => 10,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 15,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 12,
                'created_at' => '2019-01-08 08:57:56',
                'updated_at' => '2019-01-08 08:57:56',
            ),
            38 => 
            array (
                'id' => 39,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 10,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 0,
                'budget_tahunan_periode' => 12,
                'created_at' => '2019-01-08 09:07:50',
                'updated_at' => '2019-01-08 09:07:50',
            ),
            39 => 
            array (
                'id' => 40,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 14,
                'created_at' => '2019-01-09 01:36:27',
                'updated_at' => '2019-01-09 01:36:27',
            ),
            40 => 
            array (
                'id' => 41,
                'month' => 6,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 14,
                'created_at' => '2019-01-09 01:37:32',
                'updated_at' => '2019-01-09 01:37:32',
            ),
            41 => 
            array (
                'id' => 42,
                'month' => 11,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 15,
                'desember' => 10,
                'budget_tahunan_periode' => 14,
                'created_at' => '2019-01-09 01:40:02',
                'updated_at' => '2019-01-09 01:40:02',
            ),
            42 => 
            array (
                'id' => 43,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 14,
                'created_at' => '2019-01-09 01:41:08',
                'updated_at' => '2019-01-09 01:41:08',
            ),
            43 => 
            array (
                'id' => 44,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 15,
                'created_at' => '2019-01-09 01:42:11',
                'updated_at' => '2019-01-09 01:42:11',
            ),
            44 => 
            array (
                'id' => 45,
                'month' => 12,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 15,
                'budget_tahunan_periode' => 15,
                'created_at' => '2019-01-09 01:43:08',
                'updated_at' => '2019-01-09 01:43:08',
            ),
            45 => 
            array (
                'id' => 46,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 10,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 16,
                'created_at' => '2019-01-09 01:51:36',
                'updated_at' => '2019-01-09 01:51:36',
            ),
            46 => 
            array (
                'id' => 47,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 10,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 17,
                'created_at' => '2019-01-09 04:43:55',
                'updated_at' => '2019-01-09 04:43:55',
            ),
            47 => 
            array (
                'id' => 48,
                'month' => 6,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 10,
                'agustus' => 10,
                'september' => 10,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 17,
                'created_at' => '2019-01-09 04:45:07',
                'updated_at' => '2019-01-09 04:45:07',
            ),
            48 => 
            array (
                'id' => 49,
                'month' => 9,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 15,
                'oktober' => 10,
                'november' => 10,
                'desember' => 10,
                'budget_tahunan_periode' => 17,
                'created_at' => '2019-01-09 04:46:10',
                'updated_at' => '2019-01-09 04:46:10',
            ),
            49 => 
            array (
                'id' => 50,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 18,
                'created_at' => '2019-01-16 13:20:35',
                'updated_at' => '2019-01-16 13:20:35',
            ),
            50 => 
            array (
                'id' => 51,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:23:33',
                'updated_at' => '2019-01-16 23:23:33',
            ),
            51 => 
            array (
                'id' => 52,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 20,
                'created_at' => '2019-01-16 23:24:30',
                'updated_at' => '2019-01-16 23:24:30',
            ),
            52 => 
            array (
                'id' => 53,
                'month' => 2,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 18,
                'created_at' => '2019-01-16 23:26:02',
                'updated_at' => '2019-01-16 23:26:02',
            ),
            53 => 
            array (
                'id' => 54,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 30,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 18,
                'created_at' => '2019-01-16 23:26:38',
                'updated_at' => '2019-01-16 23:26:38',
            ),
            54 => 
            array (
                'id' => 55,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 30,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 18,
                'created_at' => '2019-01-16 23:27:21',
                'updated_at' => '2019-01-16 23:27:21',
            ),
            55 => 
            array (
                'id' => 56,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 30,
                'desember' => 0,
                'budget_tahunan_periode' => 18,
                'created_at' => '2019-01-16 23:28:11',
                'updated_at' => '2019-01-16 23:28:11',
            ),
            56 => 
            array (
                'id' => 57,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 19,
                'created_at' => '2019-01-16 23:32:12',
                'updated_at' => '2019-01-16 23:32:12',
            ),
            57 => 
            array (
                'id' => 58,
                'month' => 2,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 30,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 19,
                'created_at' => '2019-01-16 23:33:11',
                'updated_at' => '2019-01-16 23:33:11',
            ),
            58 => 
            array (
                'id' => 59,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 30,
                'desember' => 0,
                'budget_tahunan_periode' => 19,
                'created_at' => '2019-01-16 23:33:52',
                'updated_at' => '2019-01-16 23:33:52',
            ),
            59 => 
            array (
                'id' => 60,
                'month' => 9,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 15,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 19,
                'created_at' => '2019-01-16 23:34:39',
                'updated_at' => '2019-01-16 23:34:39',
            ),
            60 => 
            array (
                'id' => 61,
                'month' => 8,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 15,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 19,
                'created_at' => '2019-01-16 23:35:14',
                'updated_at' => '2019-01-16 23:35:14',
            ),
            61 => 
            array (
                'id' => 62,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 20,
                'created_at' => '2019-01-16 23:40:22',
                'updated_at' => '2019-01-16 23:40:22',
            ),
            62 => 
            array (
                'id' => 63,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 21,
                'created_at' => '2019-01-16 23:43:41',
                'updated_at' => '2019-01-16 23:43:41',
            ),
            63 => 
            array (
                'id' => 64,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 30,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 21,
                'created_at' => '2019-01-16 23:44:24',
                'updated_at' => '2019-01-16 23:44:24',
            ),
            64 => 
            array (
                'id' => 65,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 22,
                'created_at' => '2019-01-16 23:45:10',
                'updated_at' => '2019-01-16 23:45:10',
            ),
            65 => 
            array (
                'id' => 66,
                'month' => 1,
                'januari' => 0,
                'februari' => 0,
                'maret' => 15,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 30,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 23,
                'created_at' => '2019-01-16 23:46:02',
                'updated_at' => '2019-01-16 23:46:02',
            ),
            66 => 
            array (
                'id' => 67,
                'month' => 2,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 15,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 30,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 23,
                'created_at' => '2019-01-16 23:46:40',
                'updated_at' => '2019-01-16 23:46:40',
            ),
            67 => 
            array (
                'id' => 68,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 30,
                'desember' => 0,
                'budget_tahunan_periode' => 23,
                'created_at' => '2019-01-16 23:47:28',
                'updated_at' => '2019-01-16 23:47:28',
            ),
            68 => 
            array (
                'id' => 69,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 30,
                'budget_tahunan_periode' => 23,
                'created_at' => '2019-01-16 23:48:03',
                'updated_at' => '2019-01-16 23:48:03',
            ),
            69 => 
            array (
                'id' => 70,
                'month' => 9,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 15,
                'desember' => 0,
                'budget_tahunan_periode' => 23,
                'created_at' => '2019-01-16 23:48:34',
                'updated_at' => '2019-01-16 23:48:34',
            ),
            70 => 
            array (
                'id' => 71,
                'month' => 3,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 15,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 30,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:49:47',
                'updated_at' => '2019-01-16 23:49:47',
            ),
            71 => 
            array (
                'id' => 72,
                'month' => 4,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 15,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 30,
                'desember' => 0,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:50:26',
                'updated_at' => '2019-01-16 23:50:26',
            ),
            72 => 
            array (
                'id' => 73,
                'month' => 5,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 15,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 0,
                'desember' => 30,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:50:59',
                'updated_at' => '2019-01-16 23:50:59',
            ),
            73 => 
            array (
                'id' => 74,
                'month' => 7,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 15,
                'oktober' => 0,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:51:44',
                'updated_at' => '2019-01-16 23:51:44',
            ),
            74 => 
            array (
                'id' => 75,
                'month' => 9,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 0,
                'november' => 15,
                'desember' => 0,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:52:50',
                'updated_at' => '2019-01-16 23:52:50',
            ),
            75 => 
            array (
                'id' => 76,
                'month' => 10,
                'januari' => 0,
                'februari' => 0,
                'maret' => 0,
                'april' => 0,
                'mei' => 0,
                'juni' => 0,
                'juli' => 0,
                'agustus' => 0,
                'september' => 0,
                'oktober' => 15,
                'november' => 0,
                'desember' => 0,
                'budget_tahunan_periode' => 24,
                'created_at' => '2019-01-16 23:53:31',
                'updated_at' => '2019-01-16 23:53:31',
            ),
        ));
        
        
    }
}