<?php

use Illuminate\Database\Seeder;

class BudgetTahunanUnitsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('budget_tahunan_units')->delete();
        
        \DB::table('budget_tahunan_units')->insert(array (
            0 => 
            array (
                'id' => 1,
                'budget_tahunan_id' => 504,
                'unit_type_id' => 4,
                'volume' => 404,
                'total_unit' => 4,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'harga_satuan' => 4300000,
            ),
            1 => 
            array (
                'id' => 2,
                'budget_tahunan_id' => 504,
                'unit_type_id' => 5,
                'volume' => 1407,
                'total_unit' => 21,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'harga_satuan' => 4300000,
            ),
            2 => 
            array (
                'id' => 3,
                'budget_tahunan_id' => 504,
                'unit_type_id' => 6,
                'volume' => 795,
                'total_unit' => 15,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'harga_satuan' => 4300000,
            ),
            3 => 
            array (
                'id' => 4,
                'budget_tahunan_id' => 504,
                'unit_type_id' => 7,
                'volume' => 497,
                'total_unit' => 7,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'harga_satuan' => 4300000,
            ),
            4 => 
            array (
                'id' => 5,
                'budget_tahunan_id' => 504,
                'unit_type_id' => 8,
                'volume' => 0,
                'total_unit' => 0,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'harga_satuan' => 4300000,
            ),
            5 => 
            array (
                'id' => 6,
                'budget_tahunan_id' => 504,
                'unit_type_id' => 9,
                'volume' => 0,
                'total_unit' => 0,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-26 09:57:48',
                'updated_at' => '2018-12-26 09:57:48',
                'harga_satuan' => 4300000,
            ),
            6 => 
            array (
                'id' => 9,
                'budget_tahunan_id' => 506,
                'unit_type_id' => 69,
                'volume' => 288,
                'total_unit' => 3,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-28 04:11:02',
                'updated_at' => '2018-12-28 04:11:02',
                'harga_satuan' => 4400000,
            ),
            7 => 
            array (
                'id' => 10,
                'budget_tahunan_id' => 506,
                'unit_type_id' => 70,
                'volume' => 136,
                'total_unit' => 2,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2018-12-28 04:11:02',
                'updated_at' => '2018-12-28 04:11:02',
                'harga_satuan' => 4400000,
            ),
            8 => 
            array (
                'id' => 11,
                'budget_tahunan_id' => 505,
                'unit_type_id' => 10,
                'volume' => 191,
                'total_unit' => 1,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 08:48:05',
                'updated_at' => '2019-01-08 08:48:05',
                'harga_satuan' => 4300000,
            ),
            9 => 
            array (
                'id' => 12,
                'budget_tahunan_id' => 505,
                'unit_type_id' => 11,
                'volume' => 297,
                'total_unit' => 3,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 08:48:05',
                'updated_at' => '2019-01-08 08:48:05',
                'harga_satuan' => 4300000,
            ),
            10 => 
            array (
                'id' => 14,
                'budget_tahunan_id' => 501,
                'unit_type_id' => 66,
                'volume' => 284,
                'total_unit' => 4,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:49:44',
                'updated_at' => '2019-01-08 11:49:44',
                'harga_satuan' => 4300000,
            ),
            11 => 
            array (
                'id' => 15,
                'budget_tahunan_id' => 501,
                'unit_type_id' => 67,
                'volume' => 382,
                'total_unit' => 2,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:49:44',
                'updated_at' => '2019-01-08 11:49:44',
                'harga_satuan' => 4300000,
            ),
            12 => 
            array (
                'id' => 16,
                'budget_tahunan_id' => 501,
                'unit_type_id' => 68,
                'volume' => 69,
                'total_unit' => 1,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-08 11:49:44',
                'updated_at' => '2019-01-08 11:49:44',
                'harga_satuan' => 4300000,
            ),
            13 => 
            array (
                'id' => 17,
                'budget_tahunan_id' => 509,
                'unit_type_id' => 260,
                'volume' => 567,
                'total_unit' => 7,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-09 04:42:43',
                'updated_at' => '2019-01-09 04:42:43',
                'harga_satuan' => 2500000,
            ),
            14 => 
            array (
                'id' => 18,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 268,
                'volume' => 2142,
                'total_unit' => 34,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:01:36',
                'updated_at' => '2019-01-16 12:01:36',
                'harga_satuan' => 4250000,
            ),
            15 => 
            array (
                'id' => 19,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 268,
                'volume' => 2142,
                'total_unit' => 34,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:04:08',
                'updated_at' => '2019-01-16 12:04:08',
                'harga_satuan' => 4250000,
            ),
            16 => 
            array (
                'id' => 20,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 268,
                'volume' => 2142,
                'total_unit' => 34,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:06:13',
                'updated_at' => '2019-01-16 12:06:13',
                'harga_satuan' => 4250000,
            ),
            17 => 
            array (
                'id' => 21,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 268,
                'volume' => 2142,
                'total_unit' => 34,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4250000,
            ),
            18 => 
            array (
                'id' => 22,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 269,
                'volume' => 945,
                'total_unit' => 15,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4100000,
            ),
            19 => 
            array (
                'id' => 23,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 270,
                'volume' => 2898,
                'total_unit' => 46,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4320000,
            ),
            20 => 
            array (
                'id' => 24,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 271,
                'volume' => 252,
                'total_unit' => 4,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4320000,
            ),
            21 => 
            array (
                'id' => 25,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 275,
                'volume' => 189,
                'total_unit' => 3,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4340000,
            ),
            22 => 
            array (
                'id' => 26,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 278,
                'volume' => 1118,
                'total_unit' => 13,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4330000,
            ),
            23 => 
            array (
                'id' => 27,
                'budget_tahunan_id' => 515,
                'unit_type_id' => 277,
                'volume' => 2666,
                'total_unit' => 31,
                'satuan' => 'm2',
                'nilai' => NULL,
                'created_by' => 9999,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'created_at' => '2019-01-16 12:07:28',
                'updated_at' => '2019-01-16 12:07:28',
                'harga_satuan' => 4200000,
            ),
        ));
        
        
    }
}