<?php

use Illuminate\Database\Seeder;

class HppDevCostSummaryReportsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hpp_dev_cost_summary_reports')->delete();
        
        \DB::table('hpp_dev_cost_summary_reports')->insert(array (
            0 => 
            array (
                'id' => 1,
                'project_id' => 3,
                'project_kawasan_id' => NULL,
                'efisiensi' => 54,
                'luas_netto' => 84981.89999999999417923390865325927734375,
                'luas_bruto' => 156934.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 0.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'project_id' => 3,
                'project_kawasan_id' => 49,
                'efisiensi' => 55,
                'luas_netto' => 9474.0,
                'luas_bruto' => 17128.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 7786138254.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 2725675274.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'project_id' => 3,
                'project_kawasan_id' => 50,
                'efisiensi' => 50,
                'luas_netto' => 23201.9000000000014551915228366851806640625,
                'luas_bruto' => 46868.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 7804264161.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 0.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'project_id' => 3,
                'project_kawasan_id' => 65,
                'efisiensi' => 81,
                'luas_netto' => 5384.0,
                'luas_bruto' => 6661.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 4496129484.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 6826782277.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'project_id' => 3,
                'project_kawasan_id' => 66,
                'efisiensi' => 58,
                'luas_netto' => 28439.0,
                'luas_bruto' => 49021.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 13694657353.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 12315547242.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'project_id' => 3,
                'project_kawasan_id' => 67,
                'efisiensi' => 51,
                'luas_netto' => 18070.0,
                'luas_bruto' => 35700.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 3854683365.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 3656012974.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'project_id' => 3,
                'project_kawasan_id' => 80,
                'efisiensi' => 27,
                'luas_netto' => 413.0,
                'luas_bruto' => 1556.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 0.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-09 13:57:29',
                'created_at' => '2019-01-09 06:57:29',
                'updated_at' => '2019-01-09 06:57:29',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'project_id' => 60,
                'project_kawasan_id' => NULL,
                'efisiensi' => 0,
                'luas_netto' => NULL,
                'luas_bruto' => NULL,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 32640852032.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => 48651232939.0,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:39:38',
                'created_at' => '2019-01-15 03:39:38',
                'updated_at' => '2019-01-15 03:39:38',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'project_id' => 60,
                'project_kawasan_id' => 79,
                'efisiensi' => 1,
                'luas_netto' => 20620.360000000000582076609134674072265625,
                'luas_bruto' => 33936.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 24915087555.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:39:45',
                'created_at' => '2019-01-15 03:39:45',
                'updated_at' => '2019-01-15 03:39:45',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'project_id' => 60,
                'project_kawasan_id' => 70,
                'efisiensi' => 0,
                'luas_netto' => 27294.4000000000014551915228366851806640625,
                'luas_bruto' => 58977.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 2615597772.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:39:53',
                'created_at' => '2019-01-15 03:39:53',
                'updated_at' => '2019-01-15 03:39:53',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'project_id' => 60,
                'project_kawasan_id' => 71,
                'efisiensi' => 1,
                'luas_netto' => 23763.68999999999869032762944698333740234375,
                'luas_bruto' => 44288.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:00',
                'created_at' => '2019-01-15 03:40:00',
                'updated_at' => '2019-01-15 03:40:00',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'project_id' => 60,
                'project_kawasan_id' => 72,
                'efisiensi' => 1,
                'luas_netto' => 34091.3499999999985448084771633148193359375,
                'luas_bruto' => 63674.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:08',
                'created_at' => '2019-01-15 03:40:08',
                'updated_at' => '2019-01-15 03:40:08',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'project_id' => 60,
                'project_kawasan_id' => 73,
                'efisiensi' => 0,
                'luas_netto' => 18028.0,
                'luas_bruto' => 49289.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:16',
                'created_at' => '2019-01-15 03:40:16',
                'updated_at' => '2019-01-15 03:40:16',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'project_id' => 60,
                'project_kawasan_id' => 74,
                'efisiensi' => 1,
                'luas_netto' => 19107.02000000000043655745685100555419921875,
                'luas_bruto' => 37237.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 5901406000.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:24',
                'created_at' => '2019-01-15 03:40:24',
                'updated_at' => '2019-01-15 03:40:24',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'project_id' => 60,
                'project_kawasan_id' => 75,
                'efisiensi' => 1,
                'luas_netto' => 28397.0,
                'luas_bruto' => 50309.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 13897081420.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:31',
                'created_at' => '2019-01-15 03:40:31',
                'updated_at' => '2019-01-15 03:40:31',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'project_id' => 60,
                'project_kawasan_id' => 76,
                'efisiensi' => 0,
                'luas_netto' => 15547.47999999999956344254314899444580078125,
                'luas_bruto' => 33079.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:39',
                'created_at' => '2019-01-15 03:40:39',
                'updated_at' => '2019-01-15 03:40:39',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'project_id' => 60,
                'project_kawasan_id' => 77,
                'efisiensi' => 0,
                'luas_netto' => 0.0,
                'luas_bruto' => 0.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:39',
                'created_at' => '2019-01-15 03:40:39',
                'updated_at' => '2019-01-15 03:40:39',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'project_id' => 60,
                'project_kawasan_id' => 78,
                'efisiensi' => 0,
                'luas_netto' => 0.0,
                'luas_bruto' => 0.0,
                'total_budget' => NULL,
                'hpp_netto' => NULL,
                'hpp_bruto' => NULL,
                'total_kontrak' => 0.0,
                'hpp_kontrak_netto' => NULL,
                'hpp_kontrak_bruto' => NULL,
                'total_kontrak_terbayar' => NULL,
                'hpp_realisasi_netto' => NULL,
                'hpp_realisasi_bruto' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'delete_by' => NULL,
                'inactive_at' => '2019-01-15 10:40:40',
                'created_at' => '2019-01-15 03:40:40',
                'updated_at' => '2019-01-15 03:40:40',
                'inactive_by' => NULL,
                'delete_at' => NULL,
            ),
        ));
        
        
    }
}