<?php

use Illuminate\Database\Seeder;

class HppUpdateDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('hpp_update_details')->delete();
        
        \DB::table('hpp_update_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'hpp_update_id' => 1,
                'budget_id' => 31,
                'created_at' => '2018-12-20 09:32:10',
                'updated_at' => '2018-12-20 09:32:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'hpp_update_id' => 1,
                'budget_id' => 32,
                'created_at' => '2018-12-20 09:32:10',
                'updated_at' => '2018-12-20 09:32:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'hpp_update_id' => 1,
                'budget_id' => 34,
                'created_at' => '2018-12-20 09:32:10',
                'updated_at' => '2018-12-20 09:32:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'hpp_update_id' => 2,
                'budget_id' => 31,
                'created_at' => '2018-12-21 03:20:10',
                'updated_at' => '2018-12-21 03:20:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'hpp_update_id' => 2,
                'budget_id' => 32,
                'created_at' => '2018-12-21 03:20:10',
                'updated_at' => '2018-12-21 03:20:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'hpp_update_id' => 2,
                'budget_id' => 36,
                'created_at' => '2018-12-21 03:20:10',
                'updated_at' => '2018-12-21 03:20:10',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'hpp_update_id' => 3,
                'budget_id' => 31,
                'created_at' => '2018-12-21 03:49:59',
                'updated_at' => '2018-12-21 03:49:59',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'hpp_update_id' => 3,
                'budget_id' => 32,
                'created_at' => '2018-12-21 03:49:59',
                'updated_at' => '2018-12-21 03:49:59',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'hpp_update_id' => 3,
                'budget_id' => 37,
                'created_at' => '2018-12-21 03:49:59',
                'updated_at' => '2018-12-21 03:49:59',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'hpp_update_id' => 4,
                'budget_id' => 39,
                'created_at' => '2018-12-28 03:35:23',
                'updated_at' => '2018-12-28 03:35:23',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'hpp_update_id' => 4,
                'budget_id' => 40,
                'created_at' => '2018-12-28 03:35:23',
                'updated_at' => '2018-12-28 03:35:23',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'hpp_update_id' => 4,
                'budget_id' => 41,
                'created_at' => '2018-12-28 03:35:23',
                'updated_at' => '2018-12-28 03:35:23',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'hpp_update_id' => 4,
                'budget_id' => 43,
                'created_at' => '2018-12-28 03:35:23',
                'updated_at' => '2018-12-28 03:35:23',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'hpp_update_id' => 4,
                'budget_id' => 45,
                'created_at' => '2018-12-28 03:35:23',
                'updated_at' => '2018-12-28 03:35:23',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'hpp_update_id' => 5,
                'budget_id' => 50,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'hpp_update_id' => 5,
                'budget_id' => 52,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'hpp_update_id' => 5,
                'budget_id' => 74,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'hpp_update_id' => 5,
                'budget_id' => 87,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'hpp_update_id' => 5,
                'budget_id' => 97,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'hpp_update_id' => 5,
                'budget_id' => 98,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'hpp_update_id' => 5,
                'budget_id' => 114,
                'created_at' => '2019-01-11 07:50:12',
                'updated_at' => '2019-01-11 07:50:12',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'hpp_update_id' => 6,
                'budget_id' => 82,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'hpp_update_id' => 6,
                'budget_id' => 104,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'hpp_update_id' => 6,
                'budget_id' => 106,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'hpp_update_id' => 6,
                'budget_id' => 107,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'hpp_update_id' => 6,
                'budget_id' => 108,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'hpp_update_id' => 6,
                'budget_id' => 110,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'hpp_update_id' => 6,
                'budget_id' => 111,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'hpp_update_id' => 6,
                'budget_id' => 112,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'hpp_update_id' => 6,
                'budget_id' => 113,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'hpp_update_id' => 6,
                'budget_id' => 115,
                'created_at' => '2019-01-15 03:57:27',
                'updated_at' => '2019-01-15 03:57:27',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'hpp_update_id' => 7,
                'budget_id' => 82,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'hpp_update_id' => 7,
                'budget_id' => 104,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'hpp_update_id' => 7,
                'budget_id' => 106,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'hpp_update_id' => 7,
                'budget_id' => 107,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'hpp_update_id' => 7,
                'budget_id' => 108,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'hpp_update_id' => 7,
                'budget_id' => 110,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'hpp_update_id' => 7,
                'budget_id' => 111,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'hpp_update_id' => 7,
                'budget_id' => 112,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'hpp_update_id' => 7,
                'budget_id' => 113,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'hpp_update_id' => 7,
                'budget_id' => 115,
                'created_at' => '2019-01-15 04:01:29',
                'updated_at' => '2019-01-15 04:01:29',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'hpp_update_id' => 9,
                'budget_id' => 50,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'hpp_update_id' => 9,
                'budget_id' => 52,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'hpp_update_id' => 9,
                'budget_id' => 74,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'hpp_update_id' => 9,
                'budget_id' => 87,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'hpp_update_id' => 9,
                'budget_id' => 97,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'hpp_update_id' => 9,
                'budget_id' => 98,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'hpp_update_id' => 9,
                'budget_id' => 114,
                'created_at' => '2019-01-17 08:05:27',
                'updated_at' => '2019-01-17 08:05:27',
                'created_by' => 24,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'hpp_update_id' => 10,
                'budget_id' => 50,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'hpp_update_id' => 10,
                'budget_id' => 52,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'hpp_update_id' => 10,
                'budget_id' => 74,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'hpp_update_id' => 10,
                'budget_id' => 87,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'hpp_update_id' => 10,
                'budget_id' => 97,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'hpp_update_id' => 10,
                'budget_id' => 98,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'hpp_update_id' => 10,
                'budget_id' => 114,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'hpp_update_id' => 10,
                'budget_id' => 117,
                'created_at' => '2019-01-18 03:01:28',
                'updated_at' => '2019-01-18 03:01:28',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'hpp_update_id' => 11,
                'budget_id' => 50,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'hpp_update_id' => 11,
                'budget_id' => 52,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'hpp_update_id' => 11,
                'budget_id' => 74,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'hpp_update_id' => 11,
                'budget_id' => 87,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'hpp_update_id' => 11,
                'budget_id' => 97,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'hpp_update_id' => 11,
                'budget_id' => 98,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'hpp_update_id' => 11,
                'budget_id' => 114,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'hpp_update_id' => 11,
                'budget_id' => 117,
                'created_at' => '2019-01-18 03:24:41',
                'updated_at' => '2019-01-18 03:24:41',
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'inactive_by' => NULL,
                'inactive_at' => NULL,
            ),
        ));
        
        
    }
}