<?php

use Illuminate\Database\Seeder;

class MappingperusahaansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mappingperusahaans')->delete();
        
        \DB::table('mappingperusahaans')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pt_id' => 1,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-07-05 06:48:39',
                'updated_at' => '2018-07-05 06:48:39',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'pt_id' => 1,
                'department_id' => 1,
                'division_id' => 9,
                'description' => NULL,
                'created_at' => '2018-07-23 10:43:04',
                'updated_at' => '2018-07-23 10:43:04',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'pt_id' => 6,
                'department_id' => 2,
                'division_id' => 1,
                'description' => NULL,
                'created_at' => '2018-07-31 07:00:00',
                'updated_at' => '2018-07-31 07:00:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'pt_id' => 8,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-09-22 01:25:14',
                'updated_at' => '2018-09-22 01:25:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'pt_id' => 9,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-10-01 20:05:57',
                'updated_at' => '2018-10-01 20:05:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'pt_id' => 9,
                'department_id' => 2,
                'division_id' => 2,
                'description' => NULL,
                'created_at' => '2018-10-01 20:06:35',
                'updated_at' => '2018-10-01 20:06:35',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'pt_id' => 9,
                'department_id' => 12,
                'division_id' => 7,
                'description' => NULL,
                'created_at' => '2018-10-01 20:06:57',
                'updated_at' => '2018-10-01 20:06:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'pt_id' => 9,
                'department_id' => 6,
                'division_id' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 20:07:12',
                'updated_at' => '2018-10-01 20:07:12',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'pt_id' => 9,
                'department_id' => 6,
                'division_id' => 23,
                'description' => NULL,
                'created_at' => '2018-10-01 20:07:44',
                'updated_at' => '2018-10-01 20:07:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'pt_id' => 9,
                'department_id' => 6,
                'division_id' => 22,
                'description' => NULL,
                'created_at' => '2018-10-01 20:08:04',
                'updated_at' => '2018-10-01 20:08:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'pt_id' => 9,
                'department_id' => 14,
                'division_id' => 13,
                'description' => NULL,
                'created_at' => '2018-10-01 20:08:49',
                'updated_at' => '2018-10-01 20:08:49',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'pt_id' => 9,
                'department_id' => 14,
                'division_id' => 15,
                'description' => NULL,
                'created_at' => '2018-10-01 20:09:15',
                'updated_at' => '2018-10-01 20:09:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'pt_id' => 9,
                'department_id' => 14,
                'division_id' => 10,
                'description' => NULL,
                'created_at' => '2018-10-01 20:10:03',
                'updated_at' => '2018-10-01 20:10:03',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            13 => 
            array (
                'id' => 15,
                'pt_id' => 9,
                'department_id' => 17,
                'division_id' => 17,
                'description' => NULL,
                'created_at' => '2018-10-01 20:10:57',
                'updated_at' => '2018-10-01 20:10:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            14 => 
            array (
                'id' => 16,
                'pt_id' => 9,
                'department_id' => 2,
                'division_id' => 4,
                'description' => NULL,
                'created_at' => '2018-10-01 20:13:03',
                'updated_at' => '2018-10-01 20:13:03',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            15 => 
            array (
                'id' => 17,
                'pt_id' => 9,
                'department_id' => 2,
                'division_id' => 9,
                'description' => NULL,
                'created_at' => '2018-10-01 20:13:44',
                'updated_at' => '2018-10-01 20:13:44',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            16 => 
            array (
                'id' => 18,
                'pt_id' => 10,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-10-01 20:49:09',
                'updated_at' => '2018-10-01 20:49:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'pt_id' => 2,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-10-01 21:03:02',
                'updated_at' => '2018-10-01 21:03:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'pt_id' => 11,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-10-04 17:01:42',
                'updated_at' => '2018-10-04 17:01:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            19 => 
            array (
                'id' => 21,
                'pt_id' => 11,
                'department_id' => 2,
                'division_id' => 4,
                'description' => NULL,
                'created_at' => '2018-10-04 17:02:09',
                'updated_at' => '2018-10-04 17:02:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            20 => 
            array (
                'id' => 22,
                'pt_id' => 10,
                'department_id' => 2,
                'division_id' => 2,
                'description' => NULL,
                'created_at' => '2018-10-05 10:09:25',
                'updated_at' => '2018-10-05 10:09:25',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            21 => 
            array (
                'id' => 23,
                'pt_id' => 25,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-10-19 07:19:20',
                'updated_at' => '2018-10-19 07:19:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'pt_id' => 24,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-10-29 10:35:54',
                'updated_at' => '2018-10-29 10:35:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'pt_id' => 48,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-11-09 11:18:08',
                'updated_at' => '2018-11-09 11:18:08',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'pt_id' => 17,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-12-20 01:39:31',
                'updated_at' => '2018-12-20 01:39:31',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            25 => 
            array (
                'id' => 27,
                'pt_id' => 27,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-12-20 01:47:06',
                'updated_at' => '2018-12-20 01:47:06',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'pt_id' => 68,
                'department_id' => 2,
                'division_id' => 16,
                'description' => NULL,
                'created_at' => '2018-12-26 04:09:20',
                'updated_at' => '2018-12-26 04:09:20',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
        ));
        
        
    }
}