<?php

use Illuminate\Database\Seeder;

class ProjectKawasansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('project_kawasans')->delete();
        
        \DB::table('project_kawasans')->insert(array (
            0 => 
            array (
                'id' => 12,
                'project_id' => 66,
                'project_type_id' => 1,
                'code' => 'A',
                'name' => 'Kawasan BizPark',
                'lahan_status' => '0',
                'lahan_luas' => 85496.0,
                'lahan_sellable' => 48932.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => 'Migration from Erem based export at 26 Oct 2018',
                'created_at' => '2018-10-25 21:36:33',
                'updated_at' => '2018-11-22 15:27:04',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2143,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            1 => 
            array (
                'id' => 13,
                'project_id' => 82,
                'project_type_id' => 1,
                'code' => 'ND',
                'name' => 'NUSA DUA',
                'lahan_status' => '0',
                'lahan_luas' => 13000.0,
                'lahan_sellable' => 12000.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-31 20:02:18',
                'updated_at' => '2018-10-31 22:39:43',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            2 => 
            array (
                'id' => 14,
                'project_id' => 82,
                'project_type_id' => 1,
                'code' => 'BW',
                'name' => 'BRANWOOD',
                'lahan_status' => '0',
                'lahan_luas' => 12000.0,
                'lahan_sellable' => 12500.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-31 20:16:02',
                'updated_at' => '2018-10-31 22:40:07',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            3 => 
            array (
                'id' => 40,
                'project_id' => 9,
                'project_type_id' => NULL,
                'code' => 'BW',
                'name' => 'BRANDWOOD',
                'lahan_status' => '0',
                'lahan_luas' => 10000.0,
                'lahan_sellable' => 8000.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-11-15 10:03:45',
                'updated_at' => '2018-11-15 10:03:46',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2629,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            4 => 
            array (
                'id' => 41,
                'project_id' => 9,
                'project_type_id' => NULL,
                'code' => 'ND',
                'name' => 'NUSADUA',
                'lahan_status' => '0',
                'lahan_luas' => 15000.0,
                'lahan_sellable' => 10000.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-11-15 10:04:30',
                'updated_at' => '2018-11-15 10:04:30',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => 37,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2630,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            5 => 
            array (
                'id' => 42,
                'project_id' => 9,
                'project_type_id' => NULL,
                'code' => '34',
                'name' => '12',
                'lahan_status' => '0',
                'lahan_luas' => 12.0,
                'lahan_sellable' => 2.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-17 08:26:50',
                'updated_at' => '2018-12-17 08:26:50',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            6 => 
            array (
                'id' => 43,
                'project_id' => 9,
                'project_type_id' => NULL,
                'code' => '34',
                'name' => '12',
                'lahan_status' => '0',
                'lahan_luas' => 12.0,
                'lahan_sellable' => 2.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-17 08:28:14',
                'updated_at' => '2018-12-17 08:28:14',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            7 => 
            array (
                'id' => 44,
                'project_id' => 9,
                'project_type_id' => NULL,
                'code' => '34',
                'name' => '12',
                'lahan_status' => '0',
                'lahan_luas' => 12.0,
                'lahan_sellable' => 2.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-17 08:29:42',
                'updated_at' => '2018-12-17 08:29:42',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            8 => 
            array (
                'id' => 45,
                'project_id' => 1,
                'project_type_id' => 2,
                'code' => '66',
                'name' => 'BUKIT SALVIA',
                'lahan_status' => '0',
                'lahan_luas' => 67922.0,
                'lahan_sellable' => 40823.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 09:21:17',
                'updated_at' => '2018-12-21 07:08:50',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => 42,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2581,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            9 => 
            array (
                'id' => 46,
                'project_id' => 1,
                'project_type_id' => 2,
                'code' => '69',
                'name' => 'BUKIT SAKURA',
                'lahan_status' => '0',
                'lahan_luas' => 81774.0,
                'lahan_sellable' => 44510.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 09:28:08',
                'updated_at' => '2018-12-26 04:55:31',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => 42,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2611,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            10 => 
            array (
                'id' => 47,
                'project_id' => 1,
                'project_type_id' => 2,
                'code' => '62',
                'name' => 'BUKIT ORCHID',
                'lahan_status' => '0',
                'lahan_luas' => 45645.0,
                'lahan_sellable' => 29668.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 09:30:41',
                'updated_at' => '2018-12-21 07:14:10',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => 42,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2084,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            11 => 
            array (
                'id' => 48,
                'project_id' => 1,
                'project_type_id' => 1,
                'code' => '67',
                'name' => 'RUKO ORCHID BOULEVARD',
                'lahan_status' => '0',
                'lahan_luas' => 6421.0,
                'lahan_sellable' => 2460.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 09:34:53',
                'updated_at' => '2018-12-21 07:17:30',
                'deleted_at' => NULL,
                'created_by' => 42,
                'updated_by' => 42,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2429,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            12 => 
            array (
                'id' => 49,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => '43',
                'name' => 'PEXT2',
                'lahan_status' => '0',
                'lahan_luas' => 17128.0,
                'lahan_sellable' => 9149.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 03:04:58',
                'updated_at' => '2018-12-20 03:04:58',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2165,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            13 => 
            array (
                'id' => 50,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => '37',
                'name' => 'CLOVER GARDEN',
                'lahan_status' => '0',
                'lahan_luas' => 46868.0,
                'lahan_sellable' => 23265.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 03:07:55',
                'updated_at' => '2018-12-20 03:07:55',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2617,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            14 => 
            array (
                'id' => 51,
                'project_id' => 61,
                'project_type_id' => 2,
                'code' => 'MV-NLI',
                'name' => 'NEW LIVISTONA',
                'lahan_status' => '0',
                'lahan_luas' => 18517.0,
                'lahan_sellable' => 13802.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 07:27:36',
                'updated_at' => '2018-12-20 08:05:36',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => 46,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            15 => 
            array (
                'id' => 52,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'MV-LI',
                'name' => 'MONTEVERDE LIVISTONA',
                'lahan_status' => '0',
                'lahan_luas' => 30105.0,
                'lahan_sellable' => 18402.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:12:56',
                'updated_at' => '2018-12-20 08:12:56',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            16 => 
            array (
                'id' => 53,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'MV-CA',
                'name' => 'MONTEVERDE CARYOTA',
                'lahan_status' => '0',
                'lahan_luas' => 70781.0,
                'lahan_sellable' => 43266.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:16:49',
                'updated_at' => '2018-12-20 08:16:49',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            17 => 
            array (
                'id' => 54,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'MV-AR',
                'name' => 'MONTEVERDE ARECA',
                'lahan_status' => '0',
                'lahan_luas' => 34002.0,
                'lahan_sellable' => 20784.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:19:21',
                'updated_at' => '2018-12-20 08:19:21',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            18 => 
            array (
                'id' => 55,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'MV-AT',
                'name' => 'MONTEVERDE ATALEYA',
                'lahan_status' => '0',
                'lahan_luas' => 15795.0,
                'lahan_sellable' => 9655.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:21:33',
                'updated_at' => '2018-12-20 08:21:33',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            19 => 
            array (
                'id' => 56,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'MV-AP',
                'name' => 'MONTEVERDE APHANDRA',
                'lahan_status' => '0',
                'lahan_luas' => 21405.0,
                'lahan_sellable' => 13084.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:26:03',
                'updated_at' => '2018-12-20 08:26:03',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            20 => 
            array (
                'id' => 57,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'RK-AV2',
                'name' => 'RUKO AVENUE 2',
                'lahan_status' => '0',
                'lahan_luas' => 7805.0,
                'lahan_sellable' => 3678.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:46:27',
                'updated_at' => '2018-12-20 08:46:27',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            21 => 
            array (
                'id' => 58,
                'project_id' => 61,
                'project_type_id' => NULL,
                'code' => 'RK-AV',
                'name' => 'RUKO AVENUE',
                'lahan_status' => '0',
                'lahan_luas' => 10670.0,
                'lahan_sellable' => 5042.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-20 08:49:45',
                'updated_at' => '2018-12-20 08:49:45',
                'deleted_at' => NULL,
                'created_by' => 46,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            22 => 
            array (
                'id' => 59,
                'project_id' => 1,
                'project_type_id' => NULL,
                'code' => '70',
                'name' => 'RUKO JASMINE BOULEVARD',
                'lahan_status' => '0',
                'lahan_luas' => 7172.0,
                'lahan_sellable' => 2940.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-21 07:25:45',
                'updated_at' => '2018-12-26 07:36:15',
                'deleted_at' => '2018-12-26 07:36:15',
                'created_by' => 42,
                'updated_by' => 42,
                'deleted_by' => 42,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            23 => 
            array (
                'id' => 65,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => '42',
                'name' => 'AVERSA PARK / AA EXT',
                'lahan_status' => '0',
                'lahan_luas' => 6661.0,
                'lahan_sellable' => 3380.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-27 08:58:59',
                'updated_at' => '2018-12-27 08:58:59',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2151,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            24 => 
            array (
                'id' => 66,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => '36',
            'name' => 'SPRING LAKE (BLOK BB)',
                'lahan_status' => '0',
                'lahan_luas' => 49021.0,
                'lahan_sellable' => 26749.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-27 09:10:13',
                'updated_at' => '2018-12-27 09:10:13',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2176,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            25 => 
            array (
                'id' => 67,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => '31',
                'name' => 'GRASS MERE',
                'lahan_status' => '0',
                'lahan_luas' => 35700.0,
                'lahan_sellable' => 18118.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-27 09:11:48',
                'updated_at' => '2018-12-27 09:11:48',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => 2160,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            26 => 
            array (
                'id' => 68,
                'project_id' => 9,
                'project_type_id' => NULL,
                'code' => '13',
                'name' => 'TIGA BELAS',
                'lahan_status' => '0',
                'lahan_luas' => 400.0,
                'lahan_sellable' => 380.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-12-31 08:11:10',
                'updated_at' => '2018-12-31 08:11:10',
                'deleted_at' => NULL,
                'created_by' => 37,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            27 => 
            array (
                'id' => 70,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'A',
                'name' => 'A + AExt',
                'lahan_status' => '0',
                'lahan_luas' => 58977.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 06:36:19',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            28 => 
            array (
                'id' => 71,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'B',
                'name' => 'B',
                'lahan_status' => '0',
                'lahan_luas' => 44288.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 06:28:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            29 => 
            array (
                'id' => 72,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'C',
                'name' => 'C',
                'lahan_status' => '0',
                'lahan_luas' => 63674.0,
                'lahan_sellable' => 34091.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 06:29:45',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            30 => 
            array (
                'id' => 73,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'D',
                'name' => 'D',
                'lahan_status' => '0',
                'lahan_luas' => 49289.0,
                'lahan_sellable' => 18028.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 06:32:16',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            31 => 
            array (
                'id' => 74,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'Lagoon Residence',
                'name' => 'LAGOON RESIDENCE',
                'lahan_status' => '0',
                'lahan_luas' => 37237.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 07:18:45',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            32 => 
            array (
                'id' => 75,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'Fraser Park',
                'name' => 'FRASER PARK',
                'lahan_status' => '0',
                'lahan_luas' => 50309.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 07:20:26',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            33 => 
            array (
                'id' => 76,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'G',
                'name' => 'G',
                'lahan_status' => '0',
                'lahan_luas' => 33079.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 07:21:48',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            34 => 
            array (
                'id' => 77,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'H',
                'name' => 'H',
                'lahan_status' => '0',
                'lahan_luas' => 0.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 11:21:40',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            35 => 
            array (
                'id' => 78,
                'project_id' => 60,
                'project_type_id' => 2,
                'code' => 'I',
                'name' => 'I',
                'lahan_status' => '0',
                'lahan_luas' => 0.0,
                'lahan_sellable' => 1355.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-01 06:46:14',
                'updated_at' => '2019-01-14 07:31:46',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            36 => 
            array (
                'id' => 79,
                'project_id' => 60,
                'project_type_id' => 1,
                'code' => NULL,
                'name' => 'Ruko',
                'lahan_status' => '0',
                'lahan_luas' => 33936.0,
                'lahan_sellable' => 15494.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2018-10-02 13:42:58',
                'updated_at' => '2019-01-14 11:21:12',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 30,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            37 => 
            array (
                'id' => 80,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => '45',
                'name' => 'RUKO I KT',
                'lahan_status' => '0',
                'lahan_luas' => 1556.0,
                'lahan_sellable' => 409.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2019-01-09 02:07:18',
                'updated_at' => '2019-01-09 02:07:18',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            38 => 
            array (
                'id' => 81,
                'project_id' => 3,
                'project_type_id' => 2,
                'code' => '46',
                'name' => 'KAWASAN GABUNGAN',
                'lahan_status' => '0',
                'lahan_luas' => 11056.0,
                'lahan_sellable' => 5528.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2019-01-17 11:01:47',
                'updated_at' => '2019-01-18 03:16:56',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => 44,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
            39 => 
            array (
                'id' => 82,
                'project_id' => 3,
                'project_type_id' => NULL,
                'code' => 'PEXT2A',
                'name' => 'PEXT2A',
                'lahan_status' => '0',
                'lahan_luas' => 0.0,
                'lahan_sellable' => 0.0,
                'zipcode' => NULL,
                'is_kawasan' => 1,
                'description' => NULL,
                'created_at' => '2019-01-18 08:46:40',
                'updated_at' => '2019-01-18 08:46:40',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'cluster_id' => NULL,
                'status_gross' => NULL,
                'id_kawasan_erems' => NULL,
            ),
        ));
        
        
    }
}