<?php

use Illuminate\Database\Seeder;

class ProjectPtUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('project_pt_users')->delete();
        
        \DB::table('project_pt_users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'pt_id' => 1,
                'project_id' => 105,
                'description' => NULL,
                'created_at' => '2018-07-04 23:47:01',
                'updated_at' => '2018-08-15 09:26:42',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'user_id' => 9,
                'pt_id' => 4,
                'project_id' => 2076,
                'description' => NULL,
                'created_at' => '2018-07-31 00:00:00',
                'updated_at' => '2018-07-31 00:00:00',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'user_id' => 9,
                'pt_id' => 4,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-07-31 16:26:32',
                'updated_at' => '2018-07-31 16:26:32',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'user_id' => 9,
                'pt_id' => 6,
                'project_id' => 2077,
                'description' => NULL,
                'created_at' => '2018-08-14 11:33:29',
                'updated_at' => '2018-08-14 11:33:29',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'user_id' => 9,
                'pt_id' => 1,
                'project_id' => 2078,
                'description' => NULL,
                'created_at' => '2018-08-14 16:47:03',
                'updated_at' => '2018-08-14 16:47:03',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'user_id' => 9,
                'pt_id' => 6,
                'project_id' => 2078,
                'description' => NULL,
                'created_at' => '2018-08-14 07:00:00',
                'updated_at' => '2018-08-14 07:00:00',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'pt_id' => 5,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-08-23 14:16:21',
                'updated_at' => '2018-08-23 14:16:21',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'pt_id' => 1,
                'project_id' => 2079,
                'description' => NULL,
                'created_at' => '2018-09-03 13:13:38',
                'updated_at' => '2018-09-03 13:13:38',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'user_id' => 9,
                'pt_id' => 1,
                'project_id' => 2079,
                'description' => NULL,
                'created_at' => '2018-09-03 14:43:38',
                'updated_at' => '2018-09-03 14:43:38',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'user_id' => 9,
                'pt_id' => 1,
                'project_id' => 2080,
                'description' => NULL,
                'created_at' => '2018-09-05 22:52:14',
                'updated_at' => '2018-09-05 22:52:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'pt_id' => 1,
                'project_id' => 2081,
                'description' => NULL,
                'created_at' => '2018-09-06 16:13:00',
                'updated_at' => '2018-09-06 16:13:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            11 => 
            array (
                'id' => 16,
                'user_id' => 9,
                'pt_id' => 1,
                'project_id' => 2081,
                'description' => NULL,
                'created_at' => '2018-09-06 16:37:02',
                'updated_at' => '2018-09-06 16:37:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            12 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'pt_id' => 5,
                'project_id' => 2082,
                'description' => NULL,
                'created_at' => '2018-09-12 10:44:34',
                'updated_at' => '2018-09-12 10:44:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            13 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'pt_id' => 1,
                'project_id' => 2082,
                'description' => NULL,
                'created_at' => '2018-09-12 11:27:31',
                'updated_at' => '2018-09-12 11:27:31',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            14 => 
            array (
                'id' => 19,
                'user_id' => 9,
                'pt_id' => 1,
                'project_id' => 2082,
                'description' => NULL,
                'created_at' => '2018-09-12 13:01:07',
                'updated_at' => '2018-09-12 13:01:07',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            15 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'pt_id' => 7,
                'project_id' => 2083,
                'description' => NULL,
                'created_at' => '2018-09-18 13:48:30',
                'updated_at' => '2018-09-18 13:48:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            16 => 
            array (
                'id' => 22,
                'user_id' => 9,
                'pt_id' => 7,
                'project_id' => 2083,
                'description' => NULL,
                'created_at' => '2018-09-19 13:21:11',
                'updated_at' => '2018-09-19 13:21:11',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            17 => 
            array (
                'id' => 23,
                'user_id' => 20,
                'pt_id' => 8,
                'project_id' => 2084,
                'description' => NULL,
                'created_at' => '2018-09-21 10:47:30',
                'updated_at' => '2018-09-21 10:47:30',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            18 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'pt_id' => 8,
                'project_id' => 2086,
                'description' => NULL,
                'created_at' => '2018-09-27 10:22:10',
                'updated_at' => '2018-09-27 10:22:10',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            19 => 
            array (
                'id' => 25,
                'user_id' => 4,
                'pt_id' => 8,
                'project_id' => 2086,
                'description' => NULL,
                'created_at' => '2018-09-27 10:22:28',
                'updated_at' => '2018-09-27 10:22:28',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            20 => 
            array (
                'id' => 26,
                'user_id' => 21,
                'pt_id' => 9,
                'project_id' => 2087,
                'description' => NULL,
                'created_at' => '2018-09-27 13:51:40',
                'updated_at' => '2018-09-27 13:51:40',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-01 10:16:47',
                'updated_at' => '2018-10-01 10:16:47',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            22 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'pt_id' => 10,
                'project_id' => 2088,
                'description' => NULL,
                'created_at' => '2018-10-01 11:50:28',
                'updated_at' => '2018-10-01 11:50:28',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'user_id' => 9,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-01 16:44:18',
                'updated_at' => '2018-10-01 16:44:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'pt_id' => 11,
                'project_id' => 2089,
                'description' => NULL,
                'created_at' => '2018-10-04 10:01:21',
                'updated_at' => '2018-10-04 10:01:21',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            25 => 
            array (
                'id' => 34,
                'user_id' => 25,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-07 05:28:03',
                'updated_at' => '2018-10-07 05:28:03',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 26,
            ),
            26 => 
            array (
                'id' => 35,
                'user_id' => 26,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-07 05:29:15',
                'updated_at' => '2018-10-07 05:29:15',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            27 => 
            array (
                'id' => 36,
                'user_id' => 27,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-07 05:31:45',
                'updated_at' => '2018-10-07 05:31:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            28 => 
            array (
                'id' => 37,
                'user_id' => 28,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-07 06:36:43',
                'updated_at' => '2018-10-07 06:36:43',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 26,
            ),
            29 => 
            array (
                'id' => 38,
                'user_id' => 29,
                'pt_id' => 2,
                'project_id' => 2075,
                'description' => NULL,
                'created_at' => '2018-10-07 07:04:12',
                'updated_at' => '2018-10-07 07:04:12',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => NULL,
            ),
            30 => 
            array (
                'id' => 40,
                'user_id' => 24,
                'pt_id' => 11,
                'project_id' => 2088,
                'description' => NULL,
                'created_at' => '2018-10-09 21:10:52',
                'updated_at' => '2018-10-09 21:10:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            31 => 
            array (
                'id' => 43,
                'user_id' => 31,
                'pt_id' => 24,
                'project_id' => 66,
                'description' => NULL,
                'created_at' => '2018-10-29 03:32:17',
                'updated_at' => '2018-10-29 03:32:17',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 24,
            ),
            32 => 
            array (
                'id' => 44,
                'user_id' => 32,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-10-29 20:37:00',
                'updated_at' => '2018-10-29 20:37:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            33 => 
            array (
                'id' => 45,
                'user_id' => 37,
                'pt_id' => 48,
                'project_id' => 9,
                'description' => NULL,
                'created_at' => '2018-11-09 04:17:37',
                'updated_at' => '2018-11-09 04:17:37',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 40,
            ),
            34 => 
            array (
                'id' => 47,
                'user_id' => 25,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-11-09 04:32:56',
                'updated_at' => '2018-11-09 04:32:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            35 => 
            array (
                'id' => 48,
                'user_id' => 28,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-11-09 04:33:57',
                'updated_at' => '2018-11-09 04:33:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            36 => 
            array (
                'id' => 49,
                'user_id' => 38,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-11-09 04:44:57',
                'updated_at' => '2018-11-09 04:44:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            37 => 
            array (
                'id' => 50,
                'user_id' => 39,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-11-09 08:52:50',
                'updated_at' => '2018-11-09 08:52:50',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            38 => 
            array (
                'id' => 51,
                'user_id' => 40,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-11-09 08:53:57',
                'updated_at' => '2018-11-09 08:53:57',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            39 => 
            array (
                'id' => 52,
                'user_id' => 41,
                'pt_id' => 1,
                'project_id' => 82,
                'description' => NULL,
                'created_at' => '2018-11-09 08:56:35',
                'updated_at' => '2018-11-09 08:56:35',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 66,
            ),
            40 => 
            array (
                'id' => 53,
                'user_id' => 38,
                'pt_id' => 48,
                'project_id' => 9,
                'description' => NULL,
                'created_at' => '2018-11-15 16:47:53',
                'updated_at' => '2018-11-15 16:47:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 40,
            ),
            41 => 
            array (
                'id' => 54,
                'user_id' => 24,
                'pt_id' => 48,
                'project_id' => 9,
                'description' => NULL,
                'created_at' => '2018-11-15 16:50:42',
                'updated_at' => '2018-11-15 16:50:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 40,
            ),
            42 => 
            array (
                'id' => 55,
                'user_id' => 28,
                'pt_id' => 48,
                'project_id' => 9,
                'description' => NULL,
                'created_at' => '2018-11-15 17:33:00',
                'updated_at' => '2018-11-15 17:33:00',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 40,
            ),
            43 => 
            array (
                'id' => 57,
                'user_id' => 25,
                'pt_id' => 48,
                'project_id' => 9,
                'description' => NULL,
                'created_at' => '2018-11-15 17:38:58',
                'updated_at' => '2018-11-15 17:38:58',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 40,
            ),
            44 => 
            array (
                'id' => 60,
                'user_id' => 24,
                'pt_id' => 17,
                'project_id' => 3,
                'description' => NULL,
                'created_at' => '2018-11-21 16:22:33',
                'updated_at' => '2018-11-21 16:22:33',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 25,
            ),
            45 => 
            array (
                'id' => 63,
                'user_id' => 24,
                'pt_id' => 25,
                'project_id' => 60,
                'description' => NULL,
                'created_at' => '2018-11-21 17:20:51',
                'updated_at' => '2018-11-21 17:20:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 26,
            ),
            46 => 
            array (
                'id' => 64,
                'user_id' => 24,
                'pt_id' => 24,
                'project_id' => 66,
                'description' => NULL,
                'created_at' => '2018-11-22 15:19:52',
                'updated_at' => '2018-11-22 15:19:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 24,
            ),
            47 => 
            array (
                'id' => 65,
                'user_id' => 42,
                'pt_id' => 2,
                'project_id' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 01:11:33',
                'updated_at' => '2018-12-19 01:11:33',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 2,
            ),
            48 => 
            array (
                'id' => 66,
                'user_id' => 24,
                'pt_id' => 2,
                'project_id' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 01:17:17',
                'updated_at' => '2018-12-19 01:17:17',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 2,
            ),
            49 => 
            array (
                'id' => 67,
                'user_id' => 43,
                'pt_id' => 2,
                'project_id' => 1,
                'description' => NULL,
                'created_at' => '2018-12-19 01:24:41',
                'updated_at' => '2018-12-19 01:24:41',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 2,
            ),
            50 => 
            array (
                'id' => 68,
                'user_id' => 44,
                'pt_id' => 17,
                'project_id' => 3,
                'description' => NULL,
                'created_at' => '2018-12-20 01:38:54',
                'updated_at' => '2018-12-20 01:38:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 25,
            ),
            51 => 
            array (
                'id' => 69,
                'user_id' => 45,
                'pt_id' => 17,
                'project_id' => 3,
                'description' => NULL,
                'created_at' => '2018-12-20 01:40:52',
                'updated_at' => '2018-12-20 01:40:52',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 25,
            ),
            52 => 
            array (
                'id' => 70,
                'user_id' => 46,
                'pt_id' => 27,
                'project_id' => 61,
                'description' => NULL,
                'created_at' => '2018-12-20 01:46:22',
                'updated_at' => '2018-12-20 01:46:22',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 27,
            ),
            53 => 
            array (
                'id' => 71,
                'user_id' => 47,
                'pt_id' => 27,
                'project_id' => 61,
                'description' => NULL,
                'created_at' => '2018-12-20 01:49:31',
                'updated_at' => '2018-12-20 01:49:31',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 27,
            ),
            54 => 
            array (
                'id' => 72,
                'user_id' => 24,
                'pt_id' => 27,
                'project_id' => 61,
                'description' => NULL,
                'created_at' => '2018-12-20 01:51:34',
                'updated_at' => '2018-12-20 01:51:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 27,
            ),
            55 => 
            array (
                'id' => 74,
                'user_id' => 48,
                'pt_id' => 68,
                'project_id' => 3,
                'description' => NULL,
                'created_at' => '2018-12-26 04:19:13',
                'updated_at' => '2018-12-26 04:19:13',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 62,
            ),
            56 => 
            array (
                'id' => 75,
                'user_id' => 30,
                'pt_id' => 25,
                'project_id' => 60,
                'description' => NULL,
                'created_at' => '2019-01-08 02:51:05',
                'updated_at' => '2019-01-08 02:51:05',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 26,
            ),
            57 => 
            array (
                'id' => 76,
                'user_id' => 26,
                'pt_id' => 25,
                'project_id' => 60,
                'description' => NULL,
                'created_at' => '2019-01-17 09:13:53',
                'updated_at' => '2019-01-17 09:13:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'project_pt' => 26,
            ),
        ));
        
        
    }
}