<?php

use Illuminate\Database\Seeder;

class ProvincesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('provinces')->delete();
        
        \DB::table('provinces')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country_id' => 87,
                'name' => ' Aceh',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'country_id' => 87,
                'name' => ' Sumatera Utara',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'country_id' => 87,
                'name' => ' Bengkulu',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'country_id' => 87,
                'name' => ' Jambi',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'country_id' => 87,
                'name' => ' Riau',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'country_id' => 87,
                'name' => ' Sumatera Barat',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'country_id' => 87,
                'name' => ' Sumatera Selatan',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'country_id' => 87,
                'name' => ' Lampung',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'country_id' => 87,
                'name' => ' Kepulauan Bangka Belitung',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 9,
            ),
            9 => 
            array (
                'id' => 10,
                'country_id' => 87,
                'name' => ' Kepulauan Riau',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 10,
            ),
            10 => 
            array (
                'id' => 11,
                'country_id' => 87,
                'name' => ' Banten',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 11,
            ),
            11 => 
            array (
                'id' => 12,
                'country_id' => 87,
                'name' => ' Jawa Barat',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 12,
            ),
            12 => 
            array (
                'id' => 13,
                'country_id' => 87,
                'name' => ' DKI Jakarta',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 13,
            ),
            13 => 
            array (
                'id' => 14,
                'country_id' => 87,
                'name' => ' Jawa Tengah',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 14,
            ),
            14 => 
            array (
                'id' => 15,
                'country_id' => 87,
                'name' => ' Jawa Timur',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 15,
            ),
            15 => 
            array (
                'id' => 16,
                'country_id' => 87,
                'name' => ' Daerah Istimewa Yogyakarta',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 16,
            ),
            16 => 
            array (
                'id' => 17,
                'country_id' => 87,
                'name' => ' Bali',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 17,
            ),
            17 => 
            array (
                'id' => 18,
                'country_id' => 87,
                'name' => ' Nusa Tenggara Barat',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 18,
            ),
            18 => 
            array (
                'id' => 19,
                'country_id' => 87,
                'name' => ' Nusa Tenggara Timur',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 19,
            ),
            19 => 
            array (
                'id' => 20,
                'country_id' => 87,
                'name' => ' Kalimantan Barat',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 20,
            ),
            20 => 
            array (
                'id' => 21,
                'country_id' => 87,
                'name' => ' Kalimantan Selatan',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 21,
            ),
            21 => 
            array (
                'id' => 22,
                'country_id' => 87,
                'name' => ' Kalimantan Tengah',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 22,
            ),
            22 => 
            array (
                'id' => 23,
                'country_id' => 87,
                'name' => ' Kalimantan Timur',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 23,
            ),
            23 => 
            array (
                'id' => 24,
                'country_id' => 87,
                'name' => ' Gorontalo',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 24,
            ),
            24 => 
            array (
                'id' => 25,
                'country_id' => 87,
                'name' => ' Sulawesi Selatan',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 25,
            ),
            25 => 
            array (
                'id' => 26,
                'country_id' => 87,
                'name' => ' Sulawesi Tenggara',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 26,
            ),
            26 => 
            array (
                'id' => 27,
                'country_id' => 87,
                'name' => ' Sulawesi Tengah',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 27,
            ),
            27 => 
            array (
                'id' => 28,
                'country_id' => 87,
                'name' => ' Sulawesi Utara',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 28,
            ),
            28 => 
            array (
                'id' => 29,
                'country_id' => 87,
                'name' => ' Sulawesi Barat',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 29,
            ),
            29 => 
            array (
                'id' => 30,
                'country_id' => 87,
                'name' => ' Maluku',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 30,
            ),
            30 => 
            array (
                'id' => 31,
                'country_id' => 87,
                'name' => ' Maluku Utara',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 31,
            ),
            31 => 
            array (
                'id' => 32,
                'country_id' => 87,
                'name' => ' Papua',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 32,
            ),
            32 => 
            array (
                'id' => 33,
                'country_id' => 87,
                'name' => ' Papua Barat',
                'description' => 'Migration from Erem based export at 18 Oct 2018',
                'created_at' => '2018-12-17 08:15:13',
                'updated_at' => '2018-12-17 08:15:13',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'province_id' => 33,
            ),
        ));
        
        
    }
}