<?php

use Illuminate\Database\Seeder;

class SpkTermynsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('spk_termyns')->delete();
        
        \DB::table('spk_termyns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'spk_id' => 2361,
                'termin' => 0,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'spk_id' => 2361,
                'termin' => 1,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'spk_id' => 2361,
                'termin' => 2,
                'progress' => '11.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'spk_id' => 2361,
                'termin' => 3,
                'progress' => '39.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'spk_id' => 2361,
                'termin' => 4,
                'progress' => '11.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'spk_id' => 2361,
                'termin' => 5,
                'progress' => '39.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'spk_id' => 2361,
                'termin' => 6,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'spk_id' => 2361,
                'termin' => 7,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'spk_id' => 2361,
                'termin' => 8,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'spk_id' => 2361,
                'termin' => 9,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'spk_id' => 2361,
                'termin' => 10,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:08:46',
                'updated_at' => '2019-01-17 09:08:46',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'spk_id' => 2362,
                'termin' => 0,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'spk_id' => 2362,
                'termin' => 1,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'spk_id' => 2362,
                'termin' => 2,
                'progress' => '11.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'spk_id' => 2362,
                'termin' => 3,
                'progress' => '39.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'spk_id' => 2362,
                'termin' => 4,
                'progress' => '11.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'spk_id' => 2362,
                'termin' => 5,
                'progress' => '39.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'spk_id' => 2362,
                'termin' => 6,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'spk_id' => 2362,
                'termin' => 7,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'spk_id' => 2362,
                'termin' => 8,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'spk_id' => 2362,
                'termin' => 9,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'spk_id' => 2362,
                'termin' => 10,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:19:53',
                'updated_at' => '2019-01-17 09:19:53',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'spk_id' => 2364,
                'termin' => 0,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'spk_id' => 2364,
                'termin' => 1,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'spk_id' => 2364,
                'termin' => 2,
                'progress' => '11.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'spk_id' => 2364,
                'termin' => 3,
                'progress' => '39.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'spk_id' => 2364,
                'termin' => 4,
                'progress' => '11.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'spk_id' => 2364,
                'termin' => 5,
                'progress' => '39.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'spk_id' => 2364,
                'termin' => 6,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'spk_id' => 2364,
                'termin' => 7,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'spk_id' => 2364,
                'termin' => 8,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'spk_id' => 2364,
                'termin' => 9,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'spk_id' => 2364,
                'termin' => 10,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:51:02',
                'updated_at' => '2019-01-17 09:51:02',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'spk_id' => 2363,
                'termin' => 0,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 10:04:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 3,
            ),
            34 => 
            array (
                'id' => 35,
                'spk_id' => 2363,
                'termin' => 1,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 10:04:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 3,
            ),
            35 => 
            array (
                'id' => 36,
                'spk_id' => 2363,
                'termin' => 2,
                'progress' => '25.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 10:04:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 3,
            ),
            36 => 
            array (
                'id' => 37,
                'spk_id' => 2363,
                'termin' => 3,
                'progress' => '25.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'spk_id' => 2363,
                'termin' => 4,
                'progress' => '25.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'spk_id' => 2363,
                'termin' => 5,
                'progress' => '25.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'spk_id' => 2363,
                'termin' => 6,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'spk_id' => 2363,
                'termin' => 7,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'spk_id' => 2363,
                'termin' => 8,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'spk_id' => 2363,
                'termin' => 9,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'spk_id' => 2363,
                'termin' => 10,
                'progress' => '0.00',
                'created_at' => '2019-01-17 09:55:14',
                'updated_at' => '2019-01-17 09:55:14',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            44 => 
            array (
                'id' => 56,
                'spk_id' => 2365,
                'termin' => 0,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 11:31:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 3,
            ),
            45 => 
            array (
                'id' => 57,
                'spk_id' => 2365,
                'termin' => 1,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 11:31:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 3,
            ),
            46 => 
            array (
                'id' => 58,
                'spk_id' => 2365,
                'termin' => 2,
                'progress' => '11.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 11:31:42',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 3,
            ),
            47 => 
            array (
                'id' => 59,
                'spk_id' => 2365,
                'termin' => 3,
                'progress' => '39.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            48 => 
            array (
                'id' => 60,
                'spk_id' => 2365,
                'termin' => 4,
                'progress' => '11.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            49 => 
            array (
                'id' => 61,
                'spk_id' => 2365,
                'termin' => 5,
                'progress' => '39.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            50 => 
            array (
                'id' => 62,
                'spk_id' => 2365,
                'termin' => 6,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            51 => 
            array (
                'id' => 63,
                'spk_id' => 2365,
                'termin' => 7,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            52 => 
            array (
                'id' => 64,
                'spk_id' => 2365,
                'termin' => 8,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            53 => 
            array (
                'id' => 65,
                'spk_id' => 2365,
                'termin' => 9,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            54 => 
            array (
                'id' => 66,
                'spk_id' => 2365,
                'termin' => 10,
                'progress' => '0.00',
                'created_at' => '2019-01-17 10:09:04',
                'updated_at' => '2019-01-17 10:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            55 => 
            array (
                'id' => 67,
                'spk_id' => 1894,
                'termin' => 0,
                'progress' => '0.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 1,
            ),
            56 => 
            array (
                'id' => 68,
                'spk_id' => 1894,
                'termin' => 1,
                'progress' => '15.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            57 => 
            array (
                'id' => 69,
                'spk_id' => 1894,
                'termin' => 2,
                'progress' => '20.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            58 => 
            array (
                'id' => 70,
                'spk_id' => 1894,
                'termin' => 3,
                'progress' => '20.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            59 => 
            array (
                'id' => 71,
                'spk_id' => 1894,
                'termin' => 4,
                'progress' => '23.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            60 => 
            array (
                'id' => 72,
                'spk_id' => 1894,
                'termin' => 5,
                'progress' => '17.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            61 => 
            array (
                'id' => 73,
                'spk_id' => 1894,
                'termin' => 6,
                'progress' => '0.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            62 => 
            array (
                'id' => 74,
                'spk_id' => 1894,
                'termin' => 7,
                'progress' => '0.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            63 => 
            array (
                'id' => 75,
                'spk_id' => 1894,
                'termin' => 8,
                'progress' => '5.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            64 => 
            array (
                'id' => 76,
                'spk_id' => 1894,
                'termin' => 9,
                'progress' => '0.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
            65 => 
            array (
                'id' => 77,
                'spk_id' => 1894,
                'termin' => 10,
                'progress' => '0.00',
                'created_at' => '2019-01-18 03:53:54',
                'updated_at' => '2019-01-18 03:53:54',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
                'status' => 0,
            ),
        ));
        
        
    }
}