<?php

use Illuminate\Database\Seeder;

class UnitProgressDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('unit_progress_details')->delete();
        
        \DB::table('unit_progress_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'unit_progress_id' => 2032,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.31',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 09:59:01',
                'updated_at' => '2019-01-17 09:59:01',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'unit_progress_id' => 2026,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'unit_progress_id' => 2027,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'unit_progress_id' => 2028,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'unit_progress_id' => 2029,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'unit_progress_id' => 2030,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'unit_progress_id' => 2031,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'unit_progress_id' => 2033,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'unit_progress_id' => 2034,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'unit_progress_id' => 2035,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.50',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'unit_progress_id' => 2036,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:28:28',
                'updated_at' => '2019-01-17 11:28:28',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'unit_progress_id' => 2026,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'unit_progress_id' => 2027,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'unit_progress_id' => 2028,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'unit_progress_id' => 2029,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'unit_progress_id' => 2030,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'unit_progress_id' => 2031,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'unit_progress_id' => 2033,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'unit_progress_id' => 2034,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'unit_progress_id' => 2035,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.50',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'unit_progress_id' => 2036,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '4.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:11',
                'updated_at' => '2019-01-17 11:29:11',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'unit_progress_id' => 2026,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'unit_progress_id' => 2027,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'unit_progress_id' => 2028,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'unit_progress_id' => 2029,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'unit_progress_id' => 2030,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'unit_progress_id' => 2031,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'unit_progress_id' => 2033,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'unit_progress_id' => 2034,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'unit_progress_id' => 2035,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.50',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'unit_progress_id' => 2036,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-17',
                'progress_percent' => '0.50',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-17 11:29:24',
                'updated_at' => '2019-01-17 11:29:24',
                'deleted_at' => NULL,
                'created_by' => 44,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'unit_progress_id' => 1465,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-18',
                'progress_percent' => '1.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-18 07:22:49',
                'updated_at' => '2019-01-18 07:22:49',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'unit_progress_id' => 1513,
                'pic_rekanan' => NULL,
                'pic_internal' => NULL,
                'progress_date' => '2019-01-18',
                'progress_percent' => '1.00',
                'setuju_rekanan_at' => NULL,
                'setuju_internal_at' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-18 07:22:49',
                'updated_at' => '2019-01-18 07:22:49',
                'deleted_at' => NULL,
                'created_by' => 30,
                'updated_by' => NULL,
                'deleted_by' => NULL,
                'inactive_at' => NULL,
                'inactive_by' => NULL,
            ),
        ));
        
        
    }
}